### ISSUE TITLE
Does not work with securityContext runAsGroup 

### ISSUE THREAD

**Issue by howto-kubernetes-info** [telepresenceio/telepresence#1051]
In the moment telepresence is not useable with forcing a GID through a securityContext.

### What were you trying to do?

Use telepresence to swap a deployment with the local development version.

`telepresence --namespace <namespace> --swap-deployment <deployment_name> --docker-run  --rm -it  <local_name>`

### What did you expect to happen?

The deployment to be swapped.

### What happened instead?

The container in the pod created by telepresence fails to start.

### The logs in the failed container are:
```
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
```

The cause of this is that i use runAsGroup in the securityContext of the deployment but you build your image with a UID 1000 and a GID 0 and with an other GID the ssh keys are not readable.:

```
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
```

**Comment by ark3** [comment]
See also https://github.com/telepresenceio/telepresence/issues/875#issuecomment-447872305

**Comment by mrgzar** [comment]
This is exactly the issue I am hitting. Is there any news on `runAsGroup` or some workaround?

It is not working with this config:
```yaml
spec:
  securityContext:
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  ...
  containers:
     securityContext:
       allowPrivilegeEscalation: false
       readOnlyRootFilesystem: true
```

However, when `runAsGroup` is omitted telepresence properly swaps the deployment.
