### ISSUE TITLE
Unable to ping external services

### ISSUE THREAD

**Issue by benedictdudel** [telepresenceio/telepresence#1111]
Hey,

first of all I would like to thank you for this amazing project. 

Currently I am facing the following issue. I have a pod with a PHP-FPM and a nginx container. To swap out the deployment my telepresence command is:

```bash
telepresence --namespace my-namespace --expose 9000 --swap-deployment my-deployment:php-container --docker-run --rm -it -v $(pwd):/usr/local/nginx/html php-container-image
```

This works just fine. But I have several services of type externalName like:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: my-service
  namespace: my-namespace
spec:
  externalName: my-service.my-little-org.com
  ports:
  - name: default
    port: 3306
    protocol: TCP
    targetPort: 3306
  sessionAffinity: None
  type: ExternalName
```

which I cannot ping inside my local running container:

```bash
/usr/local/nginx/html $ ping my-service
PING tabappweb1-app (172.1.1.1): 56 data bytes
```

When I am connecting to my original container in k8s I can ping just fine:

```bash
/usr/local/nginx/html $ ping my-service
PING my-service (172.1.1.1): 56 data bytes
64 bytes from 172.1.1.1: seq=0 ttl=62 time=0.417 ms
64 bytes from 172.1.1.1: seq=1 ttl=62 time=0.508 ms
64 bytes from 172.1.1.1: seq=2 ttl=62 time=0.444 ms
64 bytes from 172.1.1.1: seq=3 ttl=62 time=3.023 ms
```

Can anyone guide me on what I do need to do to reach the service inside my local running container? Do I need to approve my local ip adress for my service or is it enough to just approve my k8s cluster?
