### ISSUE TITLE
First-class support for Kubeflow tfjobs

### ISSUE THREAD

**Issue by ashahab** [telepresenceio/telepresence#1238]
Kubeflow tfjobs[https://github.com/kubeflow/examples/blob/master/mnist/training/base/Worker.yaml] are a popular CRD for running distributed tensorflow jobs on Kubernetes.
The structure uses a pod template[https://github.com/kubeflow/examples/blob/master/mnist/training/base/Worker.yaml#L14], and therefore is similar to deployments supported by telepresence. 

From this original: 
```yaml
apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: $(trainingName)
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: %numWorkers%
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccount: default-editor
          containers:
          - name: tensorflow
            command:
            - /usr/bin/python
            - /opt/model.py
            - --tf-model-dir=$(modelDir)
            - --tf-export-dir=$(exportDir)
            - --tf-train-steps=$(trainSteps)
            - --tf-batch-size=$(batchSize)
            - --tf-learning-rate=$(learningRate)            
            env:
            - name: modelDir
              value: $(modelDir)
            - name: exportDir
              value: $(exportDir)
            - name: trainSteps
              value: $(trainSteps)
            - name: batchSize
              value: $(batchSize)
            - name: learningRate
              value: $(learningRate)
            image: training-image
            name: tensorflow
            workingDir: /opt
          restartPolicy: OnFailure
```
I expect telepresence can replace the tensorflow container image `training-image`(tensorflow container is always a required part of the tfjob) with it's own image. The worker replicas `%numWorkers% can be changed to 1.
The tfReplicaSpecs types can be `Worker`, `Evaluator`, `Ps`, and `Chief`. However, it's best to not generalize support for pod templates that support the notion of replicas(I think that will exclude daemonsets).
