### ISSUE TITLE
`kubectl run` creates a pod instead of a deployment as of kube 1.18

### ISSUE THREAD

**Issue by marun** [telepresenceio/telepresence#1297]
Kubernetes 1.18 removes support from `kubectl run` for creating anything but a pod:

https://kubernetes.io/docs/setup/release/notes/#kubectl

This would appear to break many of the documented examples for telepresence that rely on `kubectl run` to spin up a deployment that can be targeted for replacement.

**Comment by jtyers** [comment]
I haven't looked into the code to see whether this is a big fix or not, but there is a workaround I've just found, which is to create the deployment manually.

Create a telepresence deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-telepresence-deployment
spec:
  template:
    metadata:
      labels:
        app: telepresence
    spec:
      containers:
      - name: my-telepresence-deployment
        image: datawire/telepresence-k8s:0.104
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

Then run telepresence, instructing it to use the existing deployment:

```
telepresence -d my-telepresence-deployment [your other args here]
```

This seems to fix it for me; Telepresence starts fine and appears to proxy through to pods normally as before.


I think this isn't the first time changes in new versions of Kubernetes have broken Telepresence. As another workaround, you might want to consider allowing users to specify what `kubectl` binary to use. That way, I can download `kubectl` 1.17.x and point telepresence to use that instead of the latest version, which is installed by my distro's packaging system.

```
# if only I could do this...
telepresence --kubectl=/usr/local/bin/kubectl-1.17.4 [...etc]
```

Working with different clusters, I find I need multiple versions of kubectl installed anyway, and it is a more durable solution to when upstream changes in `kubectl` cause errors, until the underlying issue is fixed.
