### ISSUE TITLE
Telepresence pod won't start when swapping a deployment with restricted group in container security context

### ISSUE THREAD

**Issue by gregbacchus** [telepresenceio/telepresence#1398]
I have a deployment that restricts the runAsGroup in the container securityConext. When I try to start telepresence with --swap-deployment, the pod fails with the error

```
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
sshd: no hostkeys available -- exiting.
```

To reproduce

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepresence-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telepresence-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telepresence-test
    spec:
      containers:
        - image: datawire/hello-world
          name: app
          securityContext:
            runAsGroup: 1000
```

Then

```bash
telepresence --expose 8000:8000 --swap-deployment telepresence-test --run npm start
```

**Comment by ark3** [comment]
See also: #875.

**Comment by gregbacchus** [comment]
FYI, with the above example, it is **not** affected by

```yaml
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
```

That works OK, just double checked.
