### ISSUE TITLE
[v2] ports must be named?

### ISSUE THREAD

**Issue by mauricionr** [telepresenceio/telepresence#1597]
Before add a name to the port i got this error

<img width="1163" alt="Screen Shot 2021-03-23 at 11 30 44" src="https://user-images.githubusercontent.com/2263551/112162913-44926980-8bcb-11eb-9bd5-97548e371cf0.png">

the old spec without a name.

```
spec:
  type: NodePort
  selector:
    app: greyhound-dev-mauricio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

I jump into my deployment file and add a `name` to my port `name: http`

```
spec:
  type: NodePort
  selector:
    app: greyhound-dev-mauricio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
```

after that i could success intercept the requesst.

<img width="1187" alt="Screen Shot 2021-03-23 at 11 32 31" src="https://user-images.githubusercontent.com/2263551/112163108-7acfe900-8bcb-11eb-9d68-8a8bb8299884.png">

```
➜  greyhound git:(handle-unavailable-gifts) ✗ telepresence version
Client v2.1.2 (api v3)
Daemon v2.1.2 (api v3)
➜  greyhound git:(handle-unavailable-gifts) ✗ 
```

Thanks.

**Comment by LukeShu** [comment]
That's weird! We even test with `Service`s that don't have a port name.

I don't suppose you could also show us the ports definitions in your `Deployment`?

**Comment by mauricionr** [comment]
> That's weird! We even test with `Service`s that don't have a port name.
> 
> I don't suppose you could also show us the ports definitions in your `Deployment`?

the definition it was almost the same as the examples show in the output, except that in my definition i created the ports without a name

My ports before
```
$ kubectl get service example-service --output yaml
...
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
...
```

after the error i put the name

```
$ kubectl get service example-service --output yaml
...
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
...
```

and it works, i was using `telepresence version 2.1.2`

Today in a debugging session i upgraded my telepresence version, i will test with 2.1.3 and put here the output.

Thanks :)

**Comment by mauricionr** [comment]
We couldn't intercept the service without the name.

**Comment by donnyyung** [comment]
Hey @mauricionr ,

Could you maybe give us some more information on the deployment you are using and the command you are running? I tried to reproduce this error with yaml similar to what you've given:
```
---
apiVersion: v1
kind: Service
metadata:
  name: echo-easy
spec:
  type: NodePort
  selector:
    service: echo-easy
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-easy
  labels:
    service: echo-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: echo-easy
  template:
    metadata:
      labels:
        service: echo-easy
    spec:
      containers:
        - name: echo-easy
          image: jmalloc/echo-server
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
```
`telepresence intercept echo-easy --port 3000` works as expected.  

It'd also be helpful to know the telepresence intercept command you are using. 

For example, if you are using `telepresence intercept echo-easy --port 3000:http`, then that is telling telepresence that you want to intercept a service that has service port name `http`, so the error message you listed is accurate if no matching service with a port with that name exists. So in your example above, I believe you want to use `--port 3000` since you only have one port, and it should work.

**Comment by mauricionr** [comment]
here's mine before changed the `name`

```yml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: foobar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar
  template:
    metadata:
      labels:
        app: foobar
    spec:
      containers:
        - name: foobar
          image: image
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: foobar
  labels:
    app: foobar
spec:
  type: NodePort
  selector:
    app: foobar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: foobar
  namespace: default
spec:
  host: foobar.example.com.br
  prefix: /
  service: foobar:80
  connect_timeout_ms: 30000
  timeout_ms: 30000
``` 

so when i got the service output i could figure out that name was missing and to solve my problem i had to put the name.

```yml
...
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
...
```

**Comment by mauricionr** [comment]
> Hey @mauricionr ,
> 
> Could you maybe give us some more information on the deployment you are using and the command you are running? I tried to reproduce this error with yaml similar to what you've given:
> 
> ```
> ---
> apiVersion: v1
> kind: Service
> metadata:
>   name: echo-easy
> spec:
>   type: NodePort
>   selector:
>     service: echo-easy
>   ports:
>     - port: 80
>       protocol: TCP
>       targetPort: 8080
> ---
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: echo-easy
>   labels:
>     service: echo-easy
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       service: echo-easy
>   template:
>     metadata:
>       labels:
>         service: echo-easy
>     spec:
>       containers:
>         - name: echo-easy
>           image: jmalloc/echo-server
>           ports:
>             - containerPort: 8080
>           resources:
>             limits:
>               cpu: 50m
>               memory: 128Mi
> ```
> 
> `telepresence intercept echo-easy --port 3000` works as expected.
> 
> It'd also be helpful to know the telepresence intercept command you are using.
> 
> For example, if you are using `telepresence intercept echo-easy --port 3000:http`, then that is telling telepresence that you want to intercept a service that has service port name `http`, so the error message you listed is accurate if no matching service with a port with that name exists. So in your example above, I believe you want to use `--port 3000` since you only have one port, and it should work.

I was following the [docs](https://www.getambassador.io/docs/telepresence/latest/howtos/intercepts/), in the [docs](https://www.getambassador.io/docs/telepresence/latest/howtos/intercepts/) we have this example:


```
Intercept all traffic going to the service in your cluster:
telepresence intercept <service-name> --port <local-port>[:<remote-port>] --env-file <path-to-env-file>
```

```
telepresence intercept example-service --port 8080:http --env-file ~/example-service-intercept.env
```

**Comment by donnyyung** [comment]
Hey there,

Yes but in the docs the service port is listed as such:
```
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
```
so we can use `--port 8080:http` since we have that port name listed in the service. Since the service you showed us in the initial comment doesn't have a port, you should only use `--port <portLocalServiceRunningOn`.
