### ISSUE TITLE
[v2] Multiple clients fight over the traffic-manager install

### ISSUE THREAD

**Issue by rileyrohloff** [telepresenceio/telepresence#1617]
We have namespaces in our cluster for ephemeral testing environments that we'd like our developers to start using. Telepresencev2 seems like the best option, however we're now seeing that you can't have more than one connection to a cluster at a time? This completely derails the idea of having multiple developers working in a cloud environment if only one can connect at a time.

EX: ```telepresence connect --mapped-namespaces my-namespace```

Spins up a traffick-manager pod in the `ambassador` namespace.

NAME                               READY   STATUS    RESTARTS   AGE
traffic-manager-765f4bb59f-zvpd2   1/1     Running   0          83s

Then if my co-worker runs the same `connect` command for tele with a different namespace, it kills my traffic-manager session and I lose connection.

NAME                               READY   STATUS    RESTARTS   AGE
traffic-manager-765f4bb59f-zvpd2   1/1     Terminating   0          120s
traffic-manager-9doaad90ak3-zvp5   1/1     Running   0          75s

Is there not a way to have multiple connections to a cluster for different developer to work through telepresence? 

Or is there a way to install the traffic-manager into a specific namespace so that at least there can be a connection per namespace?

**Comment by rileyrohloff** [comment]
@LukeShu 

Both myself and my teammate upgraded our telepresence versions to the latest release and works perfectly! 

Thank you so much for the quick response!

**Comment by scottillogical** [comment]
I worked around this issue by installing a kyverno policy that globally locks us to a specific telepresence version (credit @MattSurabian for the idea)
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-telepresence-version
spec:
  validationFailureAction: enforce
  rules:
  - name: require-telepresence-version
    match:
      resources:
        name: traffic-manager
        namespaces:
        - ambassador
        kinds:
        - Deployment
    validate:
      message: "Only telepresence 2.2.0 is currently supported until https://github.com/telepresenceio/telepresence/issues/1617 is resolved. Install it with: sudo curl -fL https://app.getambassador.io/download/tel2/darwin/amd64/2.2.0/telepresence -o /usr/local/bin/telepresence && sudo chmod a+x /usr/local/bin/telepresence"
      pattern:
        spec:
          containers:
          - name: '*'
            Image: docker.io/datawire/tel2:2.2.0
```
