### ISSUE TITLE
[v2] Using the wrong container

### ISSUE THREAD

**Issue by roychri** [telepresenceio/telepresence#1635]
### What were you trying to do?

Use Telepresence to swap a deployment  (one pod with 2 containers) running on a remote kubernetes cluster running on GKE.

### What did you expect to happen?

I expected the process to run in the right container (the one called "api").
I expected that when I intercept using bash and run `echo $TELEPRESENCE_CONTAINER` that it would return the value `api`.

### What happened instead?

The process was started on the wrong container (the one called "cloudsql-proxy").
I used bash with intercept and when running `echo $TELEPRESENCE_CONTAINER` is returned `cloudsql-proxy`.

### Environment

Command line: telepresence intercept api --workload api --service api-service --port 8080 -- bash

Version: `2.1.3`
OS: `Ubuntu 18.04.5 LTS (Bionic Beaver) (Linux flash 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)`

The deployment manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - node /app/server/start.js & pid="$!"; trap "kill -s TERM $pid; wait $pid;
          touch /opt/exit-signals/SIGTERM;" TERM; wait $pid;
        env:
        - name: DEBUG
          value: '*:error'
        image: gcr.io/my-project/myimage:mytag
        name: api
        ports:
        - containerPort: 8080
          name: api-port
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/exit-signals
          name: exit-signals
      - command:
        - /cloud_sql_proxy
        - --dir=/cloudsql
        - -instances=my-project:my-region:my-db=tcp:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        image: b.gcr.io/cloudsql-docker/gce-proxy:1.15
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - until [ -f /opt/exit-signals/SIGTERM ]; do sleep 1; done;
        name: cloudsql-proxy
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ssl-certs
        - mountPath: /cloudsql
          name: cloudsql
        - mountPath: /opt/exit-signals
          name: exit-signals
      volumes:
      - emptyDir: {}
        name: cloudsql
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: my-secret
      - hostPath:
          path: /etc/ssl/certs
          type: ""
        name: ssl-certs
      - name: google-cloud-key
        secret:
          defaultMode: 420
          secretName: my-other-secret
      - emptyDir: {}
        name: exit-signals
```

The service manifest:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-service
  namespace: dev
spec:
  clusterIP: 10.x.x.x
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  sessionAffinity: None
  type: ClusterIP
```

#### The unexpected result

```
$ telepresence intercept api --workload api --service api-service --port 8080 -- bash 
Connecting to traffic manager...
Connected to context dev (https://x.x.x.x)
Using Deployment api
intercepted
    Intercept name    : api
    State             : ACTIVE
    Workload kind     : Deployment
    Destination       : 127.0.0.1:8080
    Volume Mount Error: sshfs is not installed on your local machine
    Intercepting      : all TCP connections
$ echo $TELEPRESENCE_CONTAINER 
cloudsql-proxy
$ exit
```
