### ISSUE TITLE
Intercept service error: rewrite port name must be no more than 15 characters. which is a problem when original port name is long.

### ISSUE THREAD

**Issue by zhaoxq** [telepresenceio/telepresence#1650]
Failed to intercept a service,  please help, thanks.
```
telepresence intercept dmc-0-1616987293717418-dmc-admin --port 8443:comp-http --env-file ~/dmc-admin-intercept.env
Failed to establish intercept: Deployment.apps "dmc-0-1616987293717418-dmc-admin" is invalid: spec.template.spec.containers[0].ports[1].name: Invalid value: "tel2mv-comp-https": must be no more than 15 characters
```
Here is version info
```
telepresence version
Client v2.1.4 (api v3)
Daemon v2.1.2 (api v3)
```
in my svc
```
ports:
- name: admin-https
  port: 8443
  protocol: TCP
  targetPort: 11081
```
in my deployment
```
ports:
- containerPort: 11080
  name: comp-http
  protocol: TCP
- containerPort: 11081
  name: comp-https
  protocol: TCP
```
