### ISSUE TITLE
[v2] specify alternative repository for traffic-manager

### ISSUE THREAD

**Issue by peteroneilljr** [telepresenceio/telepresence#1691]
Support cluster security configuration where access to Dockerhub is not allowed. 

And a flag or configuration file options should be provided to specify the new repository.

Flag approach.
```
telepresence intercept deployment-name --port=3000 --traffic-manager-repo=quay.io/traffic-manager
```

configuration file `config.yaml`
```
timeouts:
  agentInstall: 1m
  intercept: 10s
traffic-manager:
  repository: quay.io/traffic-manager
```
