### ISSUE TITLE
Is there a plan to support dns query on SRV record?

### ISSUE THREAD

**Issue by johnlanni** [telepresenceio/telepresence#1863]
I found this code in `cmd/traffic/cmd/agent/client.go:120`.  It seems that telepresence's dns query only support the `A/AAAA` records, because use the `net.LookupHost` function.
```go
        go func() {
                for ctx.Err() == nil {
                        lr, err := lrStream.Recv()
                        if err != nil {
                                if ctx.Err() == nil {
                                        dlog.Debugf(ctx, "lookup request stream recv: %+v", err) // May be io.EOF
                                }
                                return
                        }
                        dlog.Debugf(ctx, "LookupRequest for %s", lr.Host)
                        addrs, err := net.LookupHost(lr.Host)
                        r := rpc.LookupHostResponse{}
                        if err == nil {
                                ips := make(iputil.IPs, len(addrs))
                                for i, addr := range addrs {
                                        ips[i] = iputil.Parse(addr)
                                }
                                dlog.Debugf(ctx, "Lookup response for %s -> %s", lr.Host, ips)
                                r.Ips = ips.BytesSlice()
                        }
                        response := rpc.LookupHostAgentResponse{
                                Session:  session,
                                Request:  lr,
                                Response: &r,
                        }
                        if _, err = manager.AgentLookupHostResponse(ctx, &response); err != nil {
                                if ctx.Err() == nil {
                                        dlog.Debugf(ctx, "lookup response: %+v %v", err, &response)
                                }
                                return
                        }
                }
        }()
```

But we use the `net.LookupSRV` function in our code. Since we want to use the dns SRV record to get the FQDN and port of the service through K8S service name.

Is there a plan to support this SRV query ?

**Comment by thallgren** [comment]
@johnlanni , there is no immediate plan to support SRV records but if there's a compelling reason to do so, then we might change that. Can you tell us more about your use case?

**Comment by johnlanni** [comment]
@thallgren , we have many micro services in our system, and every service has one or more independent ports. We use `K8S Service` for service discovery,  since the `K8S Service` mechanism will automatically create the corresponding SRV record in coredns. Because the complete service address can be obtained by the name of the service through SRV dns query, we don’t need to remember the port of each service.

This is an example service：
```yaml
apiVersion: v1
kind: Service
metadata:
  name: hepa
  namespace: default
spec:
  clusterIP: 10.99.217.177
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: admin
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    erda/component: hepa
  sessionAffinity: None
  type: ClusterIP
```

This service has three ports:
- 8080: for http api
- 8081: for grpc api
- 8082: for admin api

When we want to access the hepa's grpc api, we will use the following code to get the full address.

```go
 _, addrs, err := net.DefaultResolver.LookupSRV(context.Background(), "grpc", "tcp", "hepa")
```
