### ISSUE TITLE
How can I reproduce the --also-proxy feature that was in Telepresence 1?

### ISSUE THREAD

**Issue by maelvls** [telepresenceio/telepresence#1943]
I can't seem to be able to use `include-suffixes`. I want to replicate the behavior of `--also-proxy` that is available in Telepresence 1. The flag `--also-proxy` allows me to give a hostname e.g.

```sh
# Telepresence 1
telepresence --also-proxy example.com
```

I have a single cluster, `kind-kind`, and I added the following to my ~/.kube/config:

```yaml
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:37923
  name: kind-kind
  extensions:
    - name: telepresence.io
      extension:
        dns:
          include-suffixes: [example.com]
```

`telepresence status` still shows an empty `include suffixes:

```sh
$ telepresence connect
$ telepresence status
INFO[0000] No config found. Using default
Root Daemon: Running
  Version   : v2.3.6 (api 3)
  DNS       :
    Local IP        : <nil>
    Remote IP       : <nil>
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 4s
  Also Proxy: (0 subnets)
User Daemon: Running
  Version           : v2.3.6 (api 3)
  Ambassador Cloud  : Logged out
  Status            : Connected
  Kubernetes server : https://127.0.0.1:39419
  Kubernetes context: kind-kind
  Telepresence proxy: ON (networking to the cluster is enabled)
  Intercepts        : 0 total
```

Is that how I am supposed to be using `include-suffixes`? The `/etc/resolver/` folder never gets changed, so I am assuming the above config is not picked up.
