### ISSUE TITLE
Auto-Proxy Not Proxying Traffic to/from Subnets

### ISSUE THREAD

**Issue by nazufel** [telepresenceio/telepresence#1987]
Hello,

Here is my `telepresence status` when connected to a remote cluster:

```
telepresence status
Root Daemon: Running
  Version   : v2.4.0 (api 3)
  DNS       :
    Local IP        : <nil>
    Remote IP       : <nil>
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: [.systems]
    Timeout         : 4s
  Also Proxy: (2 subnets)
    - xxx.xxx.xxx.xxx/xx
    - xxx.xxx.xxx.xxx/xx
User Daemon: Running
  Version           : v2.4.0 (api 3)
  Ambassador Cloud  : Logged out
  Status            : Connected
  Kubernetes server : https://xxx.xxx.xxx.xxx
  Kubernetes context: gke_company-cluster-xxxx
  Telepresence proxy: ON (networking to the cluster is enabled)
  Intercepts        : 0 total

```

Here are my system settings:

```
cat /etc/redhat-release
Fedora release 34 (Thirty Four)

Linux xxx 5.13.8-200.fc34.x86_64 #1 SMP Wed Aug 4 19:59:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Here is my problem:

I am attempting to use Telepresence to connect my local workstation to a remote GKE cluster, which works great! I expected, based on reading the docs, to be able to not only be able to access other services in the cluster with their internal cluster DNS names (serviceA.namespace.svc.cluster.local), but also be able to access other cloud resources such as VMs running in GCE (db.company.systems). However, accessing resources not in the cluster (database servers on VMs) is not possible at this time. 

I followed the docs on using [auto-proxy](https://www.getambassador.io/docs/telepresence/latest/reference/config/#alsoproxy) to define subnets for the traffic manager to proxy traffic back from. Here is my kubeconfig:

```
- cluster:
    certificate-authority-data:
xxx
    extensions:
    - extension:
        also-proxy:
        - xxx.xxx.xxx.xxx/xx
        - xxx.xxx.xxx.xxx/xx
        dns:
          include-suffixes:
          - .systems
        manager:
          namespace: ambassador
      name: telepresence.io
    server: https://xxx.xxx.xxx
  name: gke_company-cluster-xxxx

```

The way I understand the docs is that I should be able to access everything the cluster has access to within those defined subnets. I cannot access them from my workstation with `ping`, `curl`, or `traceroute`. However, if I `exec` into either the `serviceA` pod or even the `traffic-manager` pod I can access the db server with the above tools. The problem is when I try to access resources outside of the cluster from my laptop. Here is a diagram of what works and doesn't work as expected:

![diagram](https://user-images.githubusercontent.com/38038720/129410433-03454ed2-54ed-44b1-a024-830aae935697.jpg)

Am I missing something? I expected to be able to access other cloud resources as if my workstation was running in the cluster. Any guidance would be appreciated. 

I have already attended a Telepresence on boarding meeting with Cindy Mullins and others. They recommended I put in a Issue for this question. 

Thanks!
