### ISSUE TITLE
Requesting an intercepted pod by IP bypasses intercept when agent was injected and service has numeric ports

### ISSUE THREAD

**Issue by josecv** [telepresenceio/telepresence#2103]
As of the current state of the `release/v2` branch, the following service will have a traffic agent injected:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: echo-auto-inject
spec:
  type: ClusterIP
  selector:
    service: echo-auto-inject
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-auto-inject
  labels:
    service: echo-auto-inject
spec:
  replicas: 1
  selector:
    matchLabels:
      service: echo-auto-inject
  template:
    metadata:
      annotations:
        telepresence.getambassador.io/inject-traffic-agent: enabled
      labels:
        service: echo-auto-inject
    spec:
      containers:
        - name: echo-auto-inject
          image: jmalloc/echo-server
          ports:
            - containerPort: 8080
          resources: {}
```

If I intercept this service and request it by DNS name, it will work:

```bash
$ telepresence intercept echo-auto-inject --port 8080
$ curl echo-auto-inject.default
Request served by 2610a8ba4f1e

HTTP/1.1 GET /

Host: echo-auto-inject.default
User-Agent: curl/7.64.1
Accept: */*
```

However, if I try to reach that same intercepted pod directly by IP, I'll get a reply from the actual application:

```bash
$ curl 10.42.0.15:8080 # or whatever the IP of the pod is
Request served by echo-auto-inject-7f9cf697d9-rlrts

HTTP/1.1 GET /

Host: 10.42.0.15:8080
User-Agent: curl/7.64.1
Accept: */*
```
