### ISSUE TITLE
[v2] Intercept not intercepting traffic with Container Approach (Docker, MacOS)

### ISSUE THREAD

**Issue by Ethan-99** [telepresenceio/telepresence#2134]
**Describe the bug**
I am attempting to use the telepresence container approach to intercept traffic to an example application following the steps in the documentation. The intercept is created successfully, but the traffic is still going to the cluster pod and not my local service that is intercepting.

**To Reproduce**
Dockerfile:
```
# Dockerfile with telepresence and its prerequisites
FROM alpine:3.13

# Install Telepresence prerequisites
RUN apk add --no-cache curl iproute2 sshfs groff nodejs npm python3 py3-pip && pip3 install --upgrade pip

RUN pip3 --no-cache-dir install --upgrade awscli

# Download and install the telepresence binary
RUN curl -fL https://app.getambassador.io/download/tel2/linux/amd64/latest/telepresence -o telepresence && \
   install -o root -g root -m 0755 telepresence /usr/local/bin/telepresence
```

Docker run command:
```
docker run --cap-add=NET_ADMIN --device /dev/net/tun:/dev/net/tun --network=host \
    -v ~/.kube/config:/root/.kube/config -v ~/.aws:/root/.aws -v ~/Documents/repos:/root/repos -it --rm tp-in-docker
```

Tp commands (now in docker container):
```
telepresence connect
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context <context name> (https://<id string>.eks.amazonaws.com)

curl example-microservice-nodejs.apm-services:80
{"bar":"foo"}

curl localhost:8080
{"bar":"foo-updated"} # change made to locally running service

telepresence intercept example-microservice-nodejs -n apm-services --port 8080:80
Using Deployment example-microservice-nodejs
intercepted
    Intercept name         : example-microservice-nodejs-apm-services
    State                  : ACTIVE
    Workload kind          : Deployment
    Destination            : 127.0.0.1:8080
    Service Port Identifier: 80
    Volume Mount Point     : /tmp/telfs-3954817350
    Intercepting           : all TCP connections
Intercepting all traffic to your service.

telepresence status
Root Daemon: Running
  Version   : v2.4.0 (api 3)
  DNS       :
    Local IP        : <nil>
    Remote IP       : <nil>
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 4s
  Also Proxy: (0 subnets)
User Daemon: Running
  Version           : v2.4.0 (api 3)
  Ambassador Cloud  : Logged out
  Status            : Connected
  Kubernetes server : https://A3E00334DA116A85E4A4D07D73019EEA.gr7.us-east-1.eks.amazonaws.com
  Kubernetes context: latest
  Telepresence proxy: ON (networking to the cluster is enabled)
  Intercepts        : 0 total
```

**Expected behavior**
Now, a `curl example-microservice-nodejs.apm-services:80` should return the local change (`{"bar":"foo-updated"}`) and instead it still returns the normal response of `{"bar":"foo"}`.

This indicates that the traffic is not getting properly proxied.

**Versions (please complete the following information):**
```
telepresence version
Client: v2.4.4 (api v3)
Root Daemon: v2.4.4 (api v3)
User Daemon: v2.4.4 (api v3)
```
 - macOS Big Sur (version 11.5.2) and Docker version 20.10.8
 - Cluster is on Amazon EKS

**Additional context**
Here are the relevant snippets of the `deployment.yaml` and `service.yaml` files:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-microservice-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-microservice-nodejs
  template:
    metadata:
      labels:
        app: example-microservice-nodejs
    spec:
      serviceAccountName: example-microservice-nodejs
      automountServiceAccountToken: true
      containers:
      - name: example-microservice-nodejs
        image: # private repo
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
            limits:
                cpu:	100m
                memory:	256Mi
            requests:
                cpu:	25m
                memory:	64Mi
```

```
apiVersion: v1
kind: Service
metadata:
  name: example-microservice-nodejs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-microservice-nodejs
  sessionAffinity: None
  type: ClusterIP
```

Logs are attached.

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/7288795/telepresence_logs.zip)
