### ISSUE TITLE
[v2] HTTPS traffic is not being routed to cluster service once traffic-agent sidecar is injected into pod

### ISSUE THREAD

**Issue by Ethan-99** [telepresenceio/telepresence#2173]
**Describe the bug**
I am using the mutating webhook to inject a traffic agent into my workload. When the traffic-agent is injected, traffic to the service, regardless of whether it is being intercepted to my local service, is not able to reach to running application.
A curl request returns a `503 service unavailable`. I can confirm that the TLS secret is being injected into the sidecar container, and that this issue is not occurring on my other services that serve HTTP traffic.

**To Reproduce**
```
$ telepresence connect
...
$ curl -ikv https://insights-ui.insights:443/ping
*   Trying 172.20.114.157...
* TCP_NODELAY set
* Connected to insights-ui.insights (172.20.114.157) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
# cert info
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /ping HTTP/1.1
> Host: insights-ui.insights
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
**HTTP/1.1 200 OK**
< X-Powered-By: Express
X-Powered-By: Express
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
< Content-Length: 2
Content-Length: 2
< ETag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
ETag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Date: Mon, 25 Oct 2021 16:02:48 GMT
Date: Mon, 25 Oct 2021 16:02:48 GMT
< Connection: keep-alive
Connection: keep-alive

< 
* Connection #0 to host insights-ui.insights left intact
OK* Closing connection 0


$ telepresence intercept insights-ui -n insights --port 3443 --http-match=PI=elucia --preview-url=false
Launching browser authentication flow...
Login successful.
Using Deployment insights-ui
intercepted
    Intercept name    : insights-ui-insights
    State             : ACTIVE
    Workload kind     : Deployment
    Destination       : 127.0.0.1:3443
    Volume Mount Error: sshfs is not installed on your local machine
    Intercepting      : HTTP requests that match all headers:
      'pi: elucia'

$ curl -ikv https://insights-ui.insights:443/ping
*   Trying 172.20.114.157...
* TCP_NODELAY set
* Connected to insights-ui.insights (172.20.114.157) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server did not agree to a protocol
* Server certificate:
# cert info
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /ping HTTP/1.1
> Host: insights-ui.insights
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
**HTTP/1.1 503 Service Unavailable**
< content-length: 95
content-length: 95
< content-type: text/plain
content-type: text/plain
< date: Mon, 25 Oct 2021 16:04:23 GMT
date: Mon, 25 Oct 2021 16:04:23 GMT
< server: envoy
server: envoy

< 
* Connection #0 to host insights-ui.insights left intact
upstream connect error or disconnect/reset before headers. reset reason: connection termination* Closing connection 0
```

**Expected behavior**
After the sidecar container is started, curl requests should still return 200.

**Versions (please complete the following information):**
 - telepresence version: 2.4.4
 - MacOS BigSur 11.6
 - EKS 1.18

**Additional context**
Below are the K8s manifests _after_ the intercept command is run and the sidecar container is launched.
Pod Spec:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    getambassador.io/inject-terminating-tls-secret: insights-ui-secret-tls
    kubernetes.io/psp: eks.privileged
    telepresence.getambassador.io/inject-service-port: https
    telepresence.getambassador.io/inject-traffic-agent: enabled
  labels:
    app: insights-ui
  name: insights-ui-85ffb78d89-zj4fl
  namespace: insights
spec:
  automountServiceAccountToken: true
  containers:
  - env:
    # ...
    # env vars
    # ...
    image: # private repo
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /ping
        port: tm-https
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 1
    name: insights-ui
    ports:
    - containerPort: 3443
      name: tm-https
      protocol: TCP
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ping
        port: tm-https
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: insights-ui-token-scddp
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  - args:
    - agent
    env:
    # ...
    # same env vars
    # ...
    - name: TELEPRESENCE_CONTAINER
      value: insights-ui
    - name: _TEL_AGENT_LOG_LEVEL
      value: info
    - name: _TEL_AGENT_NAME
      value: insights-ui
    - name: _TEL_AGENT_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: _TEL_AGENT_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: _TEL_AGENT_APP_PORT
      value: "3443"
    - name: _TEL_AGENT_APP_MOUNTS
      value: /tel_app_mounts
    - name: TELEPRESENCE_MOUNTS
      value: /var/run/secrets/kubernetes.io/serviceaccount
    - name: _TEL_AGENT_MANAGER_HOST
      value: traffic-manager.ambassador
    - name: AWS_ROLE_ARN
      value: # arn
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    envFrom:
    - secretRef:
        name: insights-secrets
    image: docker.io/datawire/ambassador-telepresence-agent:1.11.3
    imagePullPolicy: IfNotPresent
    name: traffic-agent
    ports:
    - containerPort: 9900
      name: https
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/stat
        - /tmp/agent/ready
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      runAsGroup: 7777
      runAsNonRoot: true
      runAsUser: 7777
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: insights-ui-token-scddp
      readOnly: true
    - mountPath: /tel_pod_info
      name: traffic-annotations
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: insights-ui
  serviceAccountName: insights-ui
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: aws-iam-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: sts.amazonaws.com
          expirationSeconds: 86400
          path: token
  - name: insights-ui-token-scddp
    secret:
      defaultMode: 420
      secretName: insights-ui-token-scddp
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: traffic-annotations
```

Service Spec:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"insights-ui"},"name":"insights-ui","namespace":"insights"},"spec":{"ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":"https"},{"name":"http","port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app":"insights-ui"},"type":"ClusterIP"}}
  labels:
    argocd.argoproj.io/instance: insights-ui
  name: insights-ui
  namespace: insights
spec:
  clusterIP: 172.20.114.157
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: insights-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
[daemon.log](https://github.com/telepresenceio/telepresence/files/7412180/daemon.log)
[insights-ui-85ffb78d89-zj4fl.insights.log](https://github.com/telepresenceio/telepresence/files/7412181/insights-ui-85ffb78d89-zj4fl.insights.log)
[traffic-manager-f4d6c56c6-xn2r5.ambassador.log](https://github.com/telepresenceio/telepresence/files/7412182/traffic-manager-f4d6c56c6-xn2r5.ambassador.log)
