### ISSUE TITLE
error when trying to intercept a service

### ISSUE THREAD

**Issue by mmoron** [telepresenceio/telepresence#2290]
**Describe the bug**
I'm trying to intercept a service using `telepresence intercept other --port 44328` but I'm getting an error: `telepresence: error: Failed to establish intercept: Deployment name="other" namespace="default": found no Service with a port that matches any container in this workload`.

`telepresence connect` is working fine and I'm able to access the service with `curl other.default:32001/other/foo`.

`telepresence gather-logs` result:
[logs.zip](https://github.com/telepresenceio/telepresence/files/7834735/logs.zip)

result of `kubectl get service other --output yaml`
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"other","app.kubernetes.io/managed-by":"tilt"},"name":"other","namespace":"default"},"spec":{"ports":[{"port":32001,"protocol":"TCP","targetPort":44328}],"selector":{"app":"other"}}}
  creationTimestamp: "2022-01-08T20:29:25Z"
  labels:
    app: other
    app.kubernetes.io/managed-by: tilt
  name: other
  namespace: default
  resourceVersion: "67678"
  uid: 5d5a60a2-95d0-4679-8ba4-eeacb2861b39
spec:
  clusterIP: 10.96.178.243
  clusterIPs:
  - 10.96.178.243
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 32001
    protocol: TCP
    targetPort: 44328
  selector:
    app: other
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**To Reproduce**

1. create a service using:
```
apiVersion: v1
kind: Service
metadata:
    name: other
    labels:
        app: other
spec:
    selector:
        app: other
    ports:
        - protocol: TCP
          # Port accessible inside cluster
          port: 32001
          # Port to forward to inside the pod
          targetPort: 44328
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: other
    labels:
        app: other
spec:
    replicas: 1
    selector:
        matchLabels:
            app: other
    template:
        metadata:
            labels:
                app: other
        spec:
            containers:
                - name: other
                  image: other
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 32001
```

2. start a localhost version of a service listening on port 44328

3. run `telepresence intercept other --port 44328`

**Expected behavior**
Intercept should be created

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
Client: v2.4.9 (api v3)
Root Daemon: v2.4.9 (api v3)
User Daemon: v2.4.9 (api v3)
```
 - Operating system of workstation running `telepresence` commands
 Ubuntu 20.04.2 LTS **running inside of windows WSL2**
 - Kubernetes environment and Version 
 localhost cluster created with `kind` inside of WSL2
 ```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Not sure if that is important, but I have a nginx ingress installed (but no ingress rules created) in the cluster and the service is managed with `tilt`
