### ISSUE TITLE
Unable to connect to database via proxy, password authentication failed

### ISSUE THREAD

**Issue by GrzegorzKowalik** [telepresenceio/telepresence#2304]
**Describe the bug**

I have a K8S cluster setup on EKS, and RDS database with public access disabled, DB can be connected only from the cluster.
Locally, the DB URL resolves to private IP, lets say 192.168.12.12. 
I set up `also-proxy` in kubeconfig, like 
```
- cluster:
    certificate-authority-data: [...]
    extensions:
    - extension:
        also-proxy:
        - 192.168.12.12/32
      name: telepresence.io
    server: [...]
  name: [...]
```
Without this, `psql -h 192.168.12.12` fails with `psql: error: could not connect to server: No route to host`

When I try to connect to the DB and run `psql $CONNECTION_STRING`, I get an error `psql: error: FATAL:  password authentication failed for user [...]`.

When I exec to a pod on the cluster and run the same command with the same connection string, it logs in correctly.

The databse log do not show failed authentication attempt when trying to log in from my laptop, it does if I deliberately provide wrong password when connecting from a pod. It looks like it's trying to connect to different database? I checked logs of all databases accessible from within the cluster, but not one logs failed authorization from my machine. 

**Expected behavior**
I should be able to connect to a database with public access disabled

**Versions (please complete the following information):**
 - Output of `telepresence version`
```
Client: v2.4.10 (api v3)
Root Daemon: v2.4.10 (api v3)
User Daemon: v2.4.10 (api v3)
```
 - Operating system of workstation running `telepresence` commands: `Ubuntu 20.04.3`
 - Kubernetes environment and Version: AWS EKS v1.19.13

Logs:
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/7869504/telepresence_logs.zip)
