### ISSUE TITLE
Incorrect path(s) for mutating webhook certificate and key file

### ISSUE THREAD

**Issue by cyrus-mc** [telepresenceio/telepresence#2484]
Traffic manager is coded to expect the mutating webhook certificate and key file to be mounted at /var/run/secrets/tls/crt.pem and /var/run/secrets/tls/key.pem.

This breaks with convention used by Kubernetes when creating TLS secrets, which set the key(s) to tls.crt and tls.key (certificate manager follows this convention). 

Therefore in order to use certificate manager with Telepresence you need to modify the deployment spec to the following:

```
        volumeMounts:
        - mountPath: /var/run/secrets/tls/crt.pem
          name: tls
          readOnly: true
          subPath: tls.crt
        - mountPath: /var/run/secrets/tls/key.pem
          name: tls
          readOnly: true
          subPath: tls.key
```

However even this doesn't seem to work as the CLI does some sort of validation of the installed traffic manager and if it finds differences mutates it to:

```
        volumeMounts:
        - mountPath: /var/run/secrets/tls
          name: tls
          readOnly: true
        - mountPath: /var/run/secrets/tls/crt.pem
          name: tls
          readOnly: true
          subPath: tls.crt
        - mountPath: /var/run/secrets/tls/key.pem
          name: tls
          readOnly: true
          subPath: tls.key
```

Which then causes traffic manager to crash (most likely due to conflicting mount paths - I am unable to see the exact error because once the POD fails it then appears that the CLI cleans up by deleting the actual deployment). 
**Describe the bug**

**To Reproduce**

Create mutating webhook certificate via `kubectl create tls` or use `certificate manager` to generate the certificates. This will create a secret with keys `tls.crt` and `tls.key` which when used as the secret for the mutating webhook certificates will fail since the keys don't match what is expected.

**Expected behavior**

Traffic manager should follow the convention for TLS secrets as defined by Kubernetes (https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) and followed by certificate manager. 

**Versions (please complete the following information):**

This is relevant for the latest version, 2.5.3.
