### ISSUE TITLE
Readiness probe failed: stat: can't stat '/tmp/agent/ready'

### ISSUE THREAD

**Issue by deod** [telepresenceio/telepresence#2512]
**Describe the bug**
I am trying to execute the following command with my local kubernetes cluster:
`telepresence intercept MYSERVICE -- bash`

but I get the following error in my daemon.log:

```
2022-04-07 09:29:55.2575 error   daemon/session/watch-cluster-info : WatchClusterInfo recv: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing Get \"https://pooled23772-nlb-external.dev2.wdscylla.de/api/v1/namespaces/ambassador/services/traffic-manager\": dial tcp: lookup pooled23772-nlb-external.dev2.wdscylla.de: no such host"
```

The intercept command seems to be spinning up a replicate pod with a new traffic-agent container but encounters the following error :
```
 Normal   Pulled     62m                 kubelet            Container image "docker.io/datawire/ambassador-telepresence-agent:1.11.11" already present on machine
  Normal   Created    62m                 kubelet            Created container traffic-agent
  Normal   Started    62m                 kubelet            Started container traffic-agent
  Warning  Unhealthy  3s (x377 over 62m)  kubelet            Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory
```
Since the replicate pod with traffic-agent container isnt healthy, I believe it is not proceeding with the intercept. 
Is there a workaround for this readiness prob? Am I missing anything here?

connector.log:

```
2022-04-07 16:25:19.9516 info    connector/session/CreateIntercept-0 : no agent found for Deployment MYSERVICE.default
2022-04-07 16:25:19.9519 info    connector/session/CreateIntercept-0 : In Deployment MYSERVICE.default, add traffic-agent container with image docker.io/datawire/ambassador-telepresence-agent:1.11.11.
2022-04-07 16:25:19.9519 info    connector/session/CreateIntercept-0 : In Service MYSERVICE.default, make service port api.8090 symbolic with name "tx-8090".
2022-04-07 16:26:22.3040 error   connector/session/CreateIntercept-0 : the apply timed out.  The current timeout 1m0s can be configured as "timeouts.apply" in "/Users/USER/Library/Application Support/telepresence/config.yml"
```
any help would be great, I used to use telepresence v1 with swap-deployment and it used to work like a charm.
thanks

**Comment by thallgren** [comment]
Can you please tell us a bit more about your environment. What type of cluster are you using and what version? Do you have any special security constraints on your pods? Are there any service meshes involved? Also, if you do:
```
telepresence uninstall --agents <MYSERVICE>
telepresence connect
telepresence loglevel debug
telepresence intercept <MYSERVICE>
```
does that reveal some more info (you should typically see some debug logging from the agent).

**Comment by thallgren** [comment]
Closing this as no further info was provided.

**Comment by wimmerX** [comment]
Hi @thallgren, I also encountered this problem after upgrading to v2.8.2 (api 3) today
- `kubelet describe {POD}`
> Warning  Unhealthy  96s (x2791 over 7h46m)  kubelet  Readiness probe failed: stat: can't stat '/tmp/agent/ready': No such file or directory`

- traffic-agent logs
> 2022-10-15 16:22:16.5251 info    Enhanced Traffic Agent v1.13.0
2022-10-15 16:22:16.5262 info    Adding exported mounts for container cfc-server-svc
2022-10-15 16:22:16.5264 info    new agent secrets mount path: /var/run/secrets/kubernetes.io
2022-10-15 16:22:16.5265 info    LoadConfig: processing environment...
2022-10-15 16:22:16.5265 info    LoadConfig: processing annotations...
2022-10-15 16:22:16.5265 info    LoadConfig: done
2022-10-15 16:22:16.5299 info    LoadConfig: asking traffic-manager for license information...
2022-10-15 16:22:16.5351 error   error(s) getting license: license not found
2022-10-15 16:22:16.5352 info    LoadConfig: asking traffic-manager for Ambassador Cloud configuration...
2022-10-15 16:22:16.5375 info    trying to connect to ambassador cloud at app.getambassador.io:443
2022-10-15 16:22:16.9650 info    connected to ambassador cloud at app.getambassador.io:443
2022-10-15 16:22:16.9661 info    envoy-server : Management server listening on 0
2022-10-15 16:22:16.9662 info    envoy : started command ["envoy" "-l" "" "-c" "bootstrap-ads.pb" "--base-id" "1"] : dexec.pid="16"
2022-10-15 16:22:16.9663 info    envoy :  : dexec.pid="16" dexec.stream="stdin" dexec.err="EOF"
2022-10-15 16:22:16.9925 info    envoy :  : dexec.pid="16" dexec.stream="stdout+stderr" dexec.data="error: invalid log level specified ''\n"
2022-10-15 16:22:16.9939 info    envoy : finished with error: exit status 1 : dexec.pid="16"
2022-10-15 16:22:16.9940 error   envoy : goroutine "/envoy" exited with error: exit status 1
2022-10-15 16:22:16.9940 info    :shutdown_logger : shutting down (gracefully)...
2022-10-15 16:22:26.9945 info    :shutdown_logger : shutting down (not-so-gracefully)...

**Comment by thallgren** [comment]
@wimmerX , can you provide the output of these two commands please?
```console
$ kubectl -n ambassador describe deploy traffic-manager
$ kubectl describe configmap telepresence-agents
```

**Comment by wimmerX** [comment]
@thallgren 

`kubectl -n ambassador describe deploy traffic-manager`
```
Name:                   traffic-manager
Namespace:              ambassador
CreationTimestamp:      Sat, 15 Oct 2022 23:05:39 +0800
Labels:                 app=traffic-manager
                        app.kubernetes.io/created-by=Helm
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/version=2.7.6
                        helm.sh/chart=telepresence-2.7.6
                        telepresence=manager
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: traffic-manager
                        meta.helm.sh/release-namespace: ambassador
Selector:               app=traffic-manager,telepresence=manager
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=traffic-manager
                    telepresence=manager
  Service Account:  traffic-manager
  Containers:
   traffic-manager:
    Image:       docker.io/datawire/tel2:2.7.6
    Ports:       8081/TCP, 8443/TCP, 15766/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Environment:
      LOG_LEVEL:                        info
      POD_CIDR_STRATEGY:                auto
      DNS_SERVICE_NAME:                 coredns
      DNS_SERVICE_NAMESPACE:            kube-system
      DNS_SERVICE_IP:                   
      SYSTEMA_HOST:                     app.getambassador.io
      SYSTEMA_PORT:                     443
      TELEPRESENCE_GRPC_TRACE_PORT:     15766
      TELEPRESENCE_REGISTRY:            docker.io/datawire
      TELEPRESENCE_APP_PROTO_STRATEGY:  
      AGENT_INJECT_POLICY:              OnDemand
      MANAGER_NAMESPACE:                 (v1:metadata.namespace)
      TELEPRESENCE_MANAGER_POD_IP:       (v1:status.podIP)
    Mounts:
      /var/run/secrets/tls from tls (ro)
  Volumes:
   tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mutator-webhook-tls
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   traffic-manager-67d94896b9 (1/1 replicas created)
Events:          <none>
```

`kubectl describe configmap telepresence-agents`
```
Name:         telepresence-agents
Namespace:    kubeboost
Labels:       app.kubernetes.io/created-by=traffic-manager
              app.kubernetes.io/name=telepresence-agents
              app.kubernetes.io/version=2.7.6
Annotations:  <none>
Data
====
authentication-api-svc:
----
agentImage: docker.io/datawire/ambassador-telepresence-agent:1.13.0
agentName: authentication-api-svc
containers:
- Mounts: null
  envPrefix: A_
  intercepts:
  - agentPort: 9900
    containerPort: 8000
    protocol: TCP
    serviceName: authentication-api-svc
    servicePort: 8000
    servicePortName: http
    serviceUID: fc6e38d2-d8ba-4831-98ca-ef1a019aa1cb
    targetPortNumeric: true
  mountPoint: /tel_app_mounts/authentication-api-svc
  name: authentication-api-svc
logLevel: info
managerHost: traffic-manager.ambassador
managerPort: 8081
namespace: kubeboost
tracingPort: 15766
workloadKind: Deployment
workloadName: authentication-api-svc
BinaryData
====
Events:  <none>
```
