### ISSUE TITLE
telepresence ignores include-suffixes setting

### ISSUE THREAD

**Issue by lkoniecz** [telepresenceio/telepresence#2529]
**Describe the bug**

Added following snippet to my kube config
```
- cluster:
      certificate-authority-data: cert_data
      server: server_uir
      extensions:
      - extension:
          dns:
            include-suffixes:
            - .svc
        name: telepresence.io
  name: cluster_name
```
telepresence status does not reflect that change and show empty include-suffixes

```
Root Daemon: Running
  Version   : v2.5.5 (api 3)
  DNS       :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (2 subnets)
    - 54.236.162.187/32
    - 52.22.5.94/32

```

**Expected behavior**
Include suffixes includes domain suffixes

**Versions (please complete the following information):**

```
Client: v2.5.5 (api v3)
Root Daemon: v2.5.5 (api v3)
User Daemon: v2.5.5 (api v3)
```

```Linux INV-13762 5.13.0-39-generic #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

```EKS 1.23```

problem was already reported here: https://github.com/telepresenceio/telepresence/issues/1943
