### ISSUE TITLE
Telerepresence does not intercept service

### ISSUE THREAD

**Issue by lkoniecz** [telepresenceio/telepresence#2544]
**Describe the bug**

After connecting to the cluster and starting an intercept original requests still target real pod.

**To Reproduce**
```
telepresence connect
telepresence intercept player-center-adapter-reward --port 8080:http --env-file ~/pca-reward.env --mount=false
```

my intercept
```
player-center-adapter-reward       : intercepted
    Intercept name         : player-center-adapter-reward
    State                  : ACTIVE
    Workload kind          : Deployment
    Destination            : 127.0.0.1:8080
    Service Port Identifier: http
    Intercepting           : all TCP connections
```

service
```
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: lky-tele
    app.kubernetes.io/name: player-center-adapter-reward
    io.cattle.field/appId: lky-tele
```

deployment
```
      containers:
        name: player-center-adapter-reward
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
...
        name: traffic-agent
        ports:
        - containerPort: 9900
          name: http
          protocol: TCP
```

my app running on the local workstation

```
sudo lsof -i -P | grep LISTEN | grep 8080
java      3734            lky  278u  IPv6 0x5d147f700613973b      0t0    TCP *:8080 (LISTEN)
```

**Expected behavior**
traffic is forwarded to my pod

**Versions (please complete the following information):**
```
Client: v2.5.5 (api v3)
Root Daemon: v2.5.5 (api v3)
User Daemon: v2.5.5 (api v3)

EKS 1.21

ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
```

**Additional context**
I don't know if its important, by my traffic-agent side car does not expose any additional ports like tx-8080
more on that here https://github.com/telepresenceio/telepresence/issues/1721
