### ISSUE TITLE
Unable to reach services in cluster

### ISSUE THREAD

**Issue by zquintana** [telepresenceio/telepresence#2575]
**Describe the bug**
I'm unable to get reach any services through the proxy. Started telepresence with connect an intercept, I also added the config for `also-proxy` like so:

```
- cluster:
    certificate-authority-data: ~ # truncated
    extensions:
    - extension:
        also-proxy:
        - 172.20.0.0/16
        - 10.150.232.52/32
        manager:
          namespace: ambassador
      name: telepresence.io
    server: ~ # truncated
  name: ~ # truncated
```
DNS is resolving properly to IP addresses in the cluster. Example `nslookup service_name` yield the expected IP addresses. Still actually trying to `curl` them I get:

```
*   Trying 172.20.91.195:8000...
* TCP_NODELAY set
* connect to 172.20.91.195 port 8000 failed: No route to host
* Failed to connect to my_service.my_ns port 8000: No route to host
* Closing connection 0
curl: (7) Failed to connect to my_service.my_ns port 8000: No route to host
```

**To Reproduce**
1. `telepresence connect`
2. `curl my_service.my_namespace:8000`
3. See error above

**Expected behavior**
I expect that the curl should respond with a response from the service.

**Versions (please complete the following information):**
Telepresence
Client: v2.5.8 (api v3)
Root Daemon: v2.5.8 (api v3)
User Daemon: v2.5.8 (api v3)

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
