### ISSUE TITLE
Telepresence on Clusters Without A kube-dns.kube-system Service Does Not Proxy Outgoing Laptop Traffic

### ISSUE THREAD

**Issue by brownz11** [telepresenceio/telepresence#2599]
**Describe the bug**

On clusters without a `kube-dns.kube-system` service Telepresence fails to proxy outgoing traffic on the laptop to the cluster. (No routes are created on the laptop, and all DNS lookups for K8s services fail)

**To Reproduce**
1. When I run "telepresence connect" against a cluster without kube-dns.kube-system
2. I see `curl -ik https://kubernetes.default` fails with `Could not resolve host`, additionally no routes are created on the client for the K8s Service Subnets
3. So I look at the Traffic Manager logs and see there's no "Using DNS IP from kube-dns.kube-system" message
4. If I create that `kube-dns.kube-system` service (with the same selectors as `rke2-coredns-rke2-coredns.kube-system`)  and restart the traffic-manager it works

**Expected behavior**

`curl -ik https://kubernetes.default` should just work perhaps via an alternative DNS discovery mechanism, or alternatively the traffic manager logs should throw an error

**Versions (please complete the following information):**
 - Output of `telepresence version`

Client: v2.6.2 (api v3)
Root Daemon: v2.6.2 (api v3)
User Daemon: v2.6.2 (api v3)

 - Operating system of workstation running `telepresence` commands
 RHEL 8.2

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine] 
 RKE2 on premise, which creates it's DNS service as `rke2-coredns-rke2-coredns.kube-system`

**Additional context**
Logs (with hostnames altered) [telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8734059/telepresence_logs.zip)

**Comment by thallgren** [comment]
That's an interesting name `rke-coredns-rke-coredns`, why is it repeated like that?

Telepresence will currently look for the following:
```
		{
			Name:      "kube-dns",
			Namespace: "kube-system",
		},
		{
			Name:      "coredns",
			Namespace: "kube-system",
		},
		{
			Name:      "dns-default",
			Namespace: "openshift-dns",
		},
```
but there seems to be no end to how different implementations choose to name this. I guess we'll need to make it configurable.

**Comment by brownz11** [comment]
It looks like it's repeated due to the way the CoreDNS chart is written (it concats the Release Name and the Chart Name for the service name).

It would be nice to have a configuration option. Another approach, and I'm not sure if it's viable, is to look for a service with the label `k8s-app = kube-dns`. Ideally anything based on CoreDNS should have the label, but I'm sure there's something out there that doesn't do that

**Comment by thallgren** [comment]
The problem is that in order to find services using labels, the traffic-manager must have permissions to list services, probably cluster-wide. In many situations the traffic-manager install needs its RBAC to be confined to a specific namespace. What we want is the actual IP of the DNS, and we can find that by doing a simple LookupIP with \<service\>.\<namespace\>.

**Comment by AlexisDucastel** [comment]
Hi !

This is indeed a problem for Rancher RKE2 cluster that use a custom DNS deployment for coredns.

An easy workaround is to create the following service in `kube-system` namespace to have a more standard DNS discovery functionnality, thus compatible with telepresence and others. Of course, it would be better to be able to customize DNS service discovery in telepresence helm values.

Here is the service that will make your telepresence work on RKE2 : 
```
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: udp-53
    port: 53
    protocol: UDP
    targetPort: 53
  - name: tcp-53
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app.kubernetes.io/instance: rke2-coredns
    app.kubernetes.io/name: rke2-coredns
    k8s-app: kube-dns
  type: ClusterIP
```

Have a nice telepresencing 😄
