### ISSUE TITLE
Can not run pro version

### ISSUE THREAD

**Issue by yuyuvn** [telepresenceio/telepresence#2615]
**Describe the bug**
I'm install with helm by this commands

```
helm repo add datawire  https://app.getambassador.io
helm repo update
helm install traffic-manager --namespace ambassador -f values.yaml --version 2.6.4 datawire/telepresence
```

with values.yaml:
```yaml
clientRbac:
  create: true

  subjects:
  - kind: Group
    name: developer-platform-user
    apiGroup: rbac.authorization.k8s.io

licenseKey:
  create: true
  secret:
    create: false

logLevel: debug
```

and a secret in the same namespace:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: systema-license
  namespace: ambassador
  labels:
    app.kubernetes.io/instance: ambassador
data:
  hostName: YXV0aC5kYXRhd2lyZS5pbw==
  license: <reducted>
type: Opaque
```

But when run traffic-manger, it show this errors:
```
2022-05-26 13:58:52.2889 warning systema/client : error talking to System A: rpc error: code = Unauthenticated desc = transport: per-RPC creds failed due to error: no apikey has been provided by a client; retrying in 5s
...
2022-05-26 13:58:53.5532 error   agent-configs : unable to get Ambassador Cloud preferred agent image: rpc error: code = Unauthenticated desc = transport: per-RPC creds failed due to error: no apikey has been provided by a client
```

In the deployment manifests, it is mounting license secret:
```yaml
           volumeMounts:
          - name: license
            mountPath: /home/telepresence
            readOnly: true
          - name: tls
            mountPath: /var/run/secrets/tls
            readOnly: true
      volumes:
      - name: license
        secret:
          defaultMode: 420
          secretName: systema-license
```

User don't have permission to edit ambassador namespace so they can't touch manifests generated from helm.

We can't intercept http:
```
telepresence: error: Failed to establish intercept: intercept in error state NO_MECHANISM: Agents for "app" do not have mechanism "http"
```

It only happen when I upgrade from 2.5.8 to 2.6.4
