### ISSUE TITLE
istio smartDNS unsupport

### ISSUE THREAD

**Issue by novvoo** [telepresenceio/telepresence#2651]
- istio smartDNS:
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-auto
spec:
  hosts:
  - auto.internal
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: STATIC
  endpoints:
  - address: 198.51.100.2
```

- command1:
```
curl -ik https://kubernetes.default
HTTP/1.1 401 Unauthorized
Cache-Control: no-cache, private
Content-Type: application/json
Date: Mon, 20 Jun 2022 05:21:36 GMT
Content-Length: 165

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
- command2:
```
curl auto.internal
curl: (6) Could not resolve host: auto.internal

```

**Comment by njayp** [comment]
Hi. We don't currently automatically detect istio networking. However, I think there is a workaround that will give you the functionality that you want. Could you try extending your kubeconfig with the `include-suffixes` option? By adding `.internal` to `include-suffixes`, all requests with that suffix will be proxied.

```
apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1/
    extensions:
    - name: telepresence.io
      extension:
        dns:
          include-suffixes:
          - .internal
  name: example-cluster
```

docs https://www.getambassador.io/docs/telepresence/latest/reference/config/#dns
