### ISSUE TITLE
Mounting volumes into a container on Windows doesn't work as expected

### ISSUE THREAD

**Issue by philomory** [telepresenceio/telepresence#2739]
**Describe the bug**
When running under Windows, and intercepting into a container using `telepresence intercept --docker-run`, volume mounting does not work. I have tried several variants, all of which fail.

Gathered logs: 
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9366353/telepresence_logs.zip)

**To Reproduce**
Setup: I have deployed the following simple workload and service:
<details>
<summary>example.yaml</summary>

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
data:
  example.txt: Hello, world!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: app
        image: docker.io/library/nginx:1.23.1
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: example-volume
          mountPath: /etc/example
      volumes:
      - name: example-volume
        configMap:
          name: example
---
apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  selector:
    app: example
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
```

</details>

1. When I run `telepresence intercept -n example example --port 8080:80 --docker-run -- -it --rm --entrypoint bash docker.io/library/nginx:1.21.3`
2. I see the following:
   ```
   Using Deployment example
   intercepted
       Intercept name         : example-example
       State                  : ACTIVE
       Workload kind          : Deployment
       Destination            : 127.0.0.1:8080
       Service Port Identifier: http
       Volume Mount Point     : T:
       Intercepting           : all TCP requests
   docker: Error response from daemon: The system cannot find the file specified.
   See 'docker run --help'.
   telepresence: error: "C:\Program Files\Docker\Docker\resources\bin\docker.exe" docker run --dns-search tel2-search --env-file 
   C:\Users\adam.gardner\AppData\Local\Temp\tel-2535509152.env --name intercept-example-example-8080 -p 8080:80 -v T::T: -it --rm --entrypoint bash docker.io/library/nginx:1.21.3: exited with 127
   ```
4. So I try `telepresence intercept -n example example --port 8080:80 --docker-mount /tmp/data --docker-run -- -it --rm --entrypoint bash docker.io/library/nginx:1.21.3`
5. Then I see nearly the same output, only with a less-wrong-seeming `-v` flag passed to docker:
    ```
    Using Deployment example
    intercepted
        Intercept name         : example-example
        State                  : ACTIVE
        Workload kind          : Deployment
        Destination            : 127.0.0.1:8080
        Service Port Identifier: http
        Volume Mount Point     : T:
        Intercepting           : all TCP requests
    docker: Error response from daemon: The system cannot find the file specified.
    See 'docker run --help'.
    telepresence: error: "C:\Program Files\Docker\Docker\resources\bin\docker.exe" docker run --dns-search tel2-search --env-file C:\Users\adam.gardner\AppData\Local\Temp\tel-2072520013.env --name intercept-example-example-8080 -p 8080:80 -v T::/tmp/data -it --rm --entrypoint bash docker.io/library/nginx:1.21.3: exited with 127
    ```
6. Then I try: `telepresence intercept -n example example --port 8080 --mount true --env-file environment`
7. This command by itself does succeed:
    ```
    Using Deployment example
    intercepted
        Intercept name         : example-example
        State                  : ACTIVE
        Workload kind          : Deployment
        Destination            : 127.0.0.1:8080
        Service Port Identifier: http
        Volume Mount Point     : T:
        Intercepting           : all TCP requests
    ```
8. However, when I try to open a container using this volume, using the command that `telepresence` was using, I get the same error (as you might expect):
    ```
    $ docker run --dns-search tel2-search --env-file environment --name intercept-example-example-8080 -p 8080:80 -v T::/tmp/data -it --rm --entrypoint bash docker.io/library/nginx:1.21.3
    docker: Error response from daemon: The system cannot find the file specified.
    See 'docker run --help'.
    ```
9. I notice that the same issue happens even with `-v C::/tmp/data`; something about the syntax itself is wrong.
10. I notice that using `-v C:/:/tmp/data` works correctly.
11. I try using that variation with the telepresence-created volume, and get, at least, a different error:
    ```
    $ docker run --dns-search tel2-search --env-file environment --name intercept-example-example-8080 -p 8080:80 -v T:/:/tmp/data -it --rm --entrypoint bash docker.io/library/nginx:1.21.3
    docker: Error response from daemon: The volume does not contain a recognized file system.
    Please make sure that all required file system drivers are loaded and that the volume is not corrupted.
    See 'docker run --help'.
    ```
12. Installing `docker plugin install vieux/sshfs` does not make a difference.
13. Note that `telepresence intercept -n example example --port 8080:80 --mount false --docker-run -- -it --rm --entrypoint bash docker.io/library/nginx:1.21.3` _does_ work, although of course the volume does not get mounted.

**Expected behavior**
`telepresence intercept --docker-run` should be able to mount volumes correctly on Windows.

**Versions (please complete the following information):**
 - Output of `telepresence version`:
    ```
    Client: v2.6.8 (api v3)
    Root Daemon: v2.6.8 (api v3)
    User Daemon: v2.6.8 (api v3)
    ```
    (this has been tested on 2.7.1 as well, with the same results, but most work was done with 2.6.8 due to other bugs in 2.7.x.
 - Operating system of workstation running `telepresence` commands: Windows 10
 - Kubernetes environment and Version: EKS 1.21.13
