### ISSUE TITLE
Guide to install Telepresence Traffic Manager without Helm (by sources?)

### ISSUE THREAD

**Issue by SomeAkk** [telepresenceio/telepresence#2747]
Hi, how i can install Telepresence Traffic Manager without using Helm?
Maybe there is any guide for it?

**Comment by thallgren** [comment]
Helm, and the needed helm chart is embedded in Telepresence so it's very easy to just do `telepresence helm install`. Will that address your concern?

**Comment by SomeAkk** [comment]
@thallgren sometimes we can't use public network, due to infosec

**Comment by thallgren** [comment]
I don't think you'll need a public network in order to do what I suggest. As I wrote, it's all embedded in Telepresence (i.e. the `telepresence` binary). If your cluster doesn't have access either, you might need to provide a values file, like so `telepresence helm install --values <values file>`, with the following content:
```
image:
  registry: <your private docker registry>
agentInjector:
  agentImage:
    registry: <your private docker registry>
```

**Comment by thallgren** [comment]
@SomeAkk if the cluster is air-gapped, you will also need to tell the traffic-manager what image to use for the traffic-manager (it normally asks Ambassador Cloud for that info), e.g.
```yaml
image:
  registry: <your private docker registry>
agentInjector:
  agentImage:
    registry: <your private docker registry>
    name: ambassador-telepresence-agent
    tag: 1.12.12
```
