### ISSUE TITLE
CreateContainerConfigError

### ISSUE THREAD

**Issue by EugeneAikashev** [telepresenceio/telepresence#2756]
**Describe the bug**
I am trying to intercept using the following command:
```
telepresence intercept -n api aikashev -p 5000
```
But receive the following error:
`telepresence: error: rpc error: code = DeadlineExceeded desc = request timed out while waiting for agent aikashev.api to arrive`

When I check the pods, I see:
```
$ kubectl -n api get pods | grep aikashev
aikashev-7c89b866cf-57d62                                         1/2     CreateContainerConfigError   0          23s
```

And there is a warning when I do a describe pod:
```
$ kubectl -n api describe pods aikashev-7c89b866cf-57d62

Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  37s               default-scheduler  Successfully assigned api/aikashev-7c89b866cf-57d62 to ip-10-66-148-213.ec2.internal
  Normal   Pulled     36s               kubelet            Container image "nginx:alpine" already present on machine
  Normal   Created    36s               kubelet            Created container app
  Normal   Started    36s               kubelet            Started container app
  Normal   Pulled     9s (x5 over 36s)  kubelet            Container image "docker.io/datawire/ambassador-telepresence-agent:1.12.9" already present on machine
  Warning  Failed     9s (x5 over 36s)  kubelet            Error: missing value for NAMESPACE_NAME, POD_NAME
```

**To Reproduce**
Here is my simple deployment and service manifests to reproduce 
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aikashev
  name: aikashev
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aikashev
  template:
    metadata:
      labels:
        app: aikashev
    spec:
      containers:
      - image: nginx:alpine
        name: app
        ports:
        - containerPort: 80
          name: http-main
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        volumeMounts:
        - name: logs-app
          mountPath: /var/log/app
          subPathExpr: $(NAMESPACE_NAME)_$(POD_NAME)
        resources: {}
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: logs-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aikashev
  name: aikashev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http-main
    name: http
  selector:
    app: aikashev

```

**Expected behavior**
Can connect successfully with Intercept

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
$ telepresence version
Client: v2.7.1 (api v3)
Root Daemon: v2.7.1 (api v3)
User Daemon: v2.7.1 (api v3)
```
 - Operating system of workstation running `telepresence` commands
 ```
$  cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
 ```
AWS EKS

$  kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-eks-a05fdea", GitCommit:"a05fdea9a04815782f9c4b08eed73bb2d78b07e3", GitTreeState:"clean", BuildDate:"2022-06-09T21:50:47Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
It seems the issue with this config - 
```
subPathExpr: $(NAMESPACE_NAME)_$(POD_NAME)
```
When sidecar `traffic-agent` replace variable like `NAMESPACE_NAME` to `_TEL_APP_A_NAMESPACE_NAME` it doesn't do it for `subPathExpr`
