### ISSUE TITLE
duplicate labels when installing via helm

### ISSUE THREAD

**Issue by gecube** [telepresenceio/telepresence#3002]
Hi !

I am trying to install telepresence with helm. When using flux, it is very important to have no duplicate labels on objects because otherwise Kustomize won't allow the 

```bash
helm repo add datawire  https://app.getambassador.io
helm repo update
helm template traffic-manager datawire/telepresence
```

Then I checked manually what's going on.

```yaml
...
# Source: telepresence/charts/ambassador-agent/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffic-manager-ambassador-agent
  labels:
    app.kubernetes.io/name: ambassador-agent <- HERE IS THE ISSUE
    helm.sh/chart: ambassador-agent-1.0.8
    app.kubernetes.io/name: ambassador-agent <- HERE IS THE ISSUE
    app.kubernetes.io/instance: traffic-manager
    app.kubernetes.io/version: "1.0.8"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traffic-manager
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.getambassador.io/role-group: traffic-manager-ambassador-agent
rules: []
...
```

and

```yaml
---
# Source: telepresence/charts/ambassador-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic-manager-ambassador-agent
  namespace: default
  labels:
    app.kubernetes.io/name: ambassador-agent  <- HERE IS THE ISSUE
    helm.sh/chart: ambassador-agent-1.0.8
    app.kubernetes.io/name: ambassador-agent <- HERE IS THE ISSUE
    app.kubernetes.io/instance: traffic-manager
    app.kubernetes.io/version: "1.0.8"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traffic-manager
```

The labels must not be duplicated.
Please fix the chart.
