### ISSUE TITLE
User has permission to list all namespaces in a multitenant cluster

### ISSUE THREAD

**Issue by Allure996** [telepresenceio/telepresence#3014]
Hello. I tried to install telepresence as a namespaced-scoped instance, to allow users to intercept and list services only in allowed namespace.

Firstly, I created a Service Account `tp-test` inside a namespace, then I installed Traffic Manager with Helm with these parameters

```
clientRbac:
  create: true
  namespaced: true
  subjects:
  - kind: ServiceAccount
    name: tp-test
    namespace: telepresence
  namespaces:
  - telepresence
managerRbac:
  create: true
  namespaced: true
  namespaces:
  - telepresence
  - telepresence-test

```

running
```
helm install traffic-manager -n telepresence-test datawire/telepresence -f telepresence.yml
```

Traffic manager is correctly installed in the namespace, but Helm installed [these](https://github.com/telepresenceio/telepresence/blob/de9d4ddd5012319c9090c5daa9704444ee5c3a0c/charts/telepresence/templates/clientRbac/cluster-scope.yaml#L14) resources too. My user, which is in a multitenant environment, has now access to ALL namespaces in the cluster, which is not correct.

Could it be better to have a role and a rolebinding for each namespace I specified in `clientRbac.namespaces`?

Am I mistaking something?

**Comment by Allure996** [comment]
Hello, any news about this fix?

**Comment by BlueIcarus** [comment]
I appear to have the same problem. I tried it with different versions of the chart, but I just can't seem to find what I'm doing wrong. I have a slightly more details configuration in my values.yaml (but that shouldn't be an issue).

```
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      agent:
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        initResources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      managerRbac:
        create: true
        namespaced: true
        namespaces:
          - test-ns
      clientRbac:
        create: true
        namespaced: true
        subjects:
          - kind: User
            name: test-ns
            apiGroup: rbac.authorization.k8s.io
        namespaces:
          - test-ns
```
This is currently block a large scale installation because I don't want users to have cluster permissions if not needed. At the moment I can't install multiple helm charts into different namespaces. Would really love to have a solution for this issue.
