### ISSUE TITLE
Telepresence cannot get services of local k8s cluster

### ISSUE THREAD

**Issue by DarwisNarvaezDev** [telepresenceio/telepresence#3053]
# Cannot see K8s services in telepresence list

*To Reproduce**
Envioronment:

OS:  Ubuntu 22.04 LTS

telepresence version
```
Client         : v2.11.1
Root Daemon    : v2.11.1
User Daemon    : v2.11.1
Traffic Manager: v2.11.1
```
Telepresence status:
```
User Daemon: Running
  Version           : v2.11.1
  Executable        : /usr/local/bin/telepresence
  Install ID        : 5b266b81-2f1a-4a87-b2ee-94d66567b7aa
  Status            : Connected
  Kubernetes server : https://192.168.59.100:8443
  Kubernetes context: minikube
  Manager namespace : ambassador
  Intercepts        : 0 total
Root Daemon: Running
  Version    : v2.11.1
  DNS        :
    Remote IP       : 127.0.0.1
    Exclude suffixes: [.com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - 192.168.59.100/32
Ambassador Cloud:
  Status      : Logged out
Traffic Manager: Connected
  Version : v2.11.1
  Mode    : single-user
Intercept Spec: Not running
```
Service
```
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4440
  selector:
    app: app
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
```
telepresence list output
```
No Workloads (Deployments, StatefulSets, or ReplicaSets)
```
1. Installed with:
```
sudo curl -fL https://app.getambassador.io/download/tel2/linux/amd64/latest/telepresence -o /usr/local/bin/telepresence

```
Then i changed downloaded file permissions as the docs said.

2. Then i ran ```telepresence helm install``` (ok)

3. ```telepresence list``` with only the service i just shared and no output list. 

**Expected behavior**
To list services in order to do interception.
