### ISSUE TITLE
Intercept package spec does not allow images coming from GCP artifact registry

### ISSUE THREAD

**Issue by Jell** [telepresenceio/telepresence#3064]
Given this spec:

```yaml
workloads:
  - name: echo
    namespace: jl-devops-test-app
    intercepts:
      - handler: echo-local
connection:
  context: "gke_treyd-development_europe-north1_treyd-development"
handlers:
  - name: echo-local
    docker:
      image: europe-north1-docker.pkg.dev/treyd-docker-images/main/jl-devops-test-app@sha256:a787565a420e9e31c09c7cfc0b758c53c8a3d333025f6da8deb29449360622bb
```

When I run:

```
telepresence intercept run my-intercept.yaml
```

I expect the intercept to be setup, but instead I get this error:

```
telepresence intercept run: error: handlers.0.docker.image: Does not match pattern '^([a-zA-Z][a-zA-Z0-9._-]+(:\d+)?/)?[a-z0-9._-]+(/[a-z0-9._-]+)?([:@][a-zA-Z0-9._-]{1,127})?$'
```

The issue is twofold:

1. the regexp doesn't allow for a nested path in the URL
2. the regexp doesn't allow for a sha tag of the form `@sha256:a787565a420e9e31c09c7cfc0b758c53c8a3d333025f6da8deb29449360622bb`

Both of those are standard in images hosted on Google Cloud Platform's Artifact Registry.

Running on Mac OS with the following versions:

```
⎪▸ telepresence version
Client         : v2.11.1
Root Daemon    : v2.11.1
User Daemon    : v2.11.1
Traffic Manager: v2.11.1
```
