### ISSUE TITLE
`telepresence uninstall --agent` returns an error when using client RBAC

### ISSUE THREAD

**Issue by lmtthws** [telepresenceio/telepresence#3096]
**Describe the bug**
When using client RBAC for the telepresence client, the `telepresence uninstall` command returns an error due to the user's role not having the necessary permissions to read the `telepresence-agent` config map created in the workload's namespace by the traffic manager.

**To Reproduce**
1. Create a service account for use with client RBAC

    ```yaml
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: telepresence-agent
      namespace: ambassador
    ```
1. Deploy Telepresence using the released helm chart and the `helm` executable (not `telepresence helm install`) and set the chart values to use client RBAC with no namespaces and the previously created service account. 

    ```yaml
    clientRbac:
      create: true
      subjects:
      - kind: ServiceAccount
        name: telepresence-agent
        namespace: ambassador
      namespaced: false
    ```

1. Get the `telepresence-agent` user's service account token and create a context or otherwise adjust the kubeconfig file so that commands are executed under that user's identity.

   ```yaml
    apiVersion: v1
    kind: Config
    clusters:
    - name: my-cluster
      cluster:
        certificate-authority-data: L...
        server: https://public.kube.api.endpoint.com:443
    current-context: default
    contexts:
    - name: default
      context:
        cluster: my-cluster
        namespace: not-my-namespace
        user: telepresence-agent
    preferences: {}
    users:
    - name: telepresence-agent
      user:
        token: ej...
    ```

1. `telepresence connect` and establish an intercept via `telepresence intercept -n my-namespace --port 8080:8181 serviceName`
1. Try to uninstall the traffic agent on the intercepted workload: `telepresence uninstall -n my-namespace -d serviceName`
1. The uninstall fails and returns the following error message:

    ```sh
    $ telepresence uninstall -n my-namespace -d serviceName
    telepresence uninstall: error: configmaps "telepresence-agents" is forbidden: User "system:serviceaccount:ambassador:telepresence-agent" cannot get resource "configmaps" in API group "" in the namespace "default"
    ```

**Expected behavior**
The uninstall command successfully removes the injected `traffic-agent` from the workload

**Versions (please complete the following information):**
 - Output of `telepresence version`: 

    ```sh
    Client         : v2.10.6
    Root Daemon    : v2.10.6
    User Daemon    : v2.10.6
    Traffic Manager: v2.10.6
    ```

 - Operating system of workstation running `telepresence` commands: Debian 11 container running out of WSL2 5.15 on Windows 10
 - Kubernetes environment and Version: Azure Kubernetes Service 1.23.12
