### ISSUE TITLE
Kube-api ServiceAcct Not Being Mounted During Telepresence Intercept

### ISSUE THREAD

**Issue by BTS-SealStorage** [telepresenceio/telepresence#3120]
**Describe the bug**
When creating an intercept for an existing deployment, the kube-api serviceacct is not mounted locally.  From the pod spec:
```
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tlwbl
      readOnly: true
```

Creating the intercept with: `TELEPRESENCE_ROOT="$(pwd)/telfs" telepresence intercept --namespace cert-manager cert-manager --port 9402 --mount=$(pwd)/telfs -- /bin/bash` 

```
cert-manager        : intercepted
   Intercept name         : cert-manager-cert-manager
   State                  : ACTIVE
   Workload kind          : Deployment
   Destination            : 127.0.0.1:9402
   Service Port Identifier: tcp-prometheus-servicemonitor
   Volume Mount Point     : /home/btsomogyi/code/github/cert-manager/_bin/server/telfs
   Intercepting           : all TCP requests
```

From the bash shell in intercept:
```
btsomogyi@framework-sealstore:~/code/github/cert-manager/_bin/server$ ls /home/btsomogyi/code/github/cert-manager/_bin/server/telfs
btsomogyi@framework-sealstore:~/code/github/cert-manager/_bin/server$ 
```
Note no contents of `telfs` directory above :point_up: 

**To Reproduce**
1. Run a pod that mounts the `/var/run/secrets/kubernetes.io/serviceaccount/token` per [this](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/) documentation, eg (from pod manifest):
```    
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tlwbl
      readOnly: true
```

Intercept the pod with telepresence:
```
TELEPRESENCE_ROOT="$(pwd)/telfs" telepresence intercept --namespace cert-manager cert-manager --port 9402 --mount=$(pwd)/telfs -- /bin/bash
```

2. I DON'T see the serviceaccount token mounted at `$(pwd)/telfs/var/run/secrets/kubernetes.io/serviceaccount/token`

**Expected behavior**
`/home/btsomogyi/code/github/cert-manager/_bin/server/telfs/var/run/secrets/kubernetes.io/serviceaccount/token` to exist while the intercept is active.

Per this telepresence [doc](https://www.getambassador.io/docs/telepresence/latest/reference/volume)

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
$ telepresence version
Client         : v2.12.1
Root Daemon    : v2.12.1
User Daemon    : v2.12.1
Traffic Manager: v2.12.1
```
 - Operating system of workstation running `telepresence` commands
Kubuntu 22.04

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
bare metal v1.26.1 (kubeadm, cillium CNI)

**Additional context**
:thinking:
