### ISSUE TITLE
Telepresence with Consul

### ISSUE THREAD

**Issue by eliesemaan6** [telepresenceio/telepresence#3232]
**Describe the bug**
I have Consul installed in my cluster for service discovery. I am trying to intercept a service with telepresence. 

Issue is similar to https://github.com/telepresenceio/telepresence/issues/2426 

The traffic agent is added to the POD but nothing gets intercepted. 
The suggestion on that issue was to use a newer version, however I am using Telepresence 2.13.3 and I have the same behavior. Is telepresence intercept supported with Consul? 

Thank you

**Comment by thallgren** [comment]
Telepresence might collide with Consul because it too uses an Envoy sidecar. Here are some things you can try:

Use different values for the Envoy ports. Create a yaml file and use `telepresence helm upgrade -f <your file>` to apply it.
```yaml
agent:
  envoy:
    serverPort: 18100
    adminPort: 19100
```
Also, to make sure that the Telepresence pod injection sees the Consul injection, try adding:
```yaml
agentInjector:
  webhook:
    reinvocationPolicy: IfNeeded
```

Look at the created pod to determine how Telepresence and Consul injected containers are configured, e.g. `kubectl get pod NNN -o yaml`.
