### ISSUE TITLE
Back-off restarting failed container tel-agent-init in pod

### ISSUE THREAD

**Issue by JCzz** [telepresenceio/telepresence#3356]
Steps:

MacOs M1 Chip
telepresence version
OSS Client         : v2.15.1
OSS Root Daemon    : v2.15.1
OSS User Daemon    : v2.15.1
OSS Traffic Manager: v2.14.2

1. kind create cluster
2. telepresence helm install
3. telepresence list
echo-deployment: ready to intercept (traffic-agent not yet installed)

Question 1. 
Why is it only deployment listed and not the services. From this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: docker.io/library/hello_go_http:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: echo-service
spec:
  selector:
    app: echo
  ports:
    # Default port used by the image
    - port: 8080
```

When trying to intercept I get:
````
telepresence intercept echo-deployment --port 8080:8080

telepresence intercept echo-deployment --port 8080:8080
telepresence intercept: error: connector.CreateIntercept: Back-off restarting failed container tel-agent-init in pod echo-deployment-b647c7d89-jsnhg_default(a43b1582-e34f-4d9a-a19e-aefe3b314abb)
The logs of Pod echo-deployment-b647c7d89-jsnhg might provide more details
````
kubectl get pods
````
NAME                               READY   STATUS       RESTARTS      AGE
echo-deployment-797db448c9-v52rl   1/1     Running      0             7m40s
echo-deployment-b647c7d89-jsnhg    0/2     Init:Error   2 (30s ago)   31s
````

logs:
````
logs echo-deployment-b647c7d89-jsnhg    
Defaulted container "echo" out of: echo, traffic-agent, tel-agent-init (init)
Error from server (BadRequest): container "echo" in pod "echo-deployment-b647c7d89-jsnhg" is waiting to start: PodInitializing
````

Any idea?

Thanks in advance
