### ISSUE TITLE
telepresence list not showing statefulsets

### ISSUE THREAD

**Issue by msvticket** [telepresenceio/telepresence#3361]
**Describe the bug**

`telepresence list` doesn't show statefulsets

**To Reproduce**
1. When I run `telepresence list`
2. I see a list of deployments in the current namespace

**Expected behavior**
I expect that also statefulsets would be listed

**Versions**

telepresence version:
OSS Client     : v2.15.1
OSS Root Daemon: v2.15.1
OSS User Daemon: v2.15.1
Traffic Manager: v2.15.1

Operating system of workstation: macOS 14.0
k8s Server Version: v1.25.12-eks-2d98532

**Comment by thallgren** [comment]
Telepresence should list interceptable statefulsets. Whether or not it's interceptable depends on if there's a service that selects it, and that the service can find a matching port.

**Comment by msvticket** [comment]
Doing intercept on this particular statefulset works fine.

**Comment by thallgren** [comment]
Do you have rbac permissions to get/list stateful sets?

**Comment by msvticket** [comment]
> Do you have rbac permissions to get/list stateful sets?

Sure, but `kubectl get` works fine.

**Comment by knlambert** [comment]
Can you try to add the label you use in your service to target the pod on the statefulset ? 

For example, if you have this service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  [...]
    selector:
        app: my-statefulset
```

Add this in the statefulset:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: my-statefulset
[...]
```
