### ISSUE TITLE
Make the namespace selector of the agent-injector webhook more configurable

### ISSUE THREAD

**Issue by thallgren** [telepresenceio/telepresence#3369]
GKE considers our agent-injector webhook [to be unsafe](https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks?&_ga=2.126734093.-1284460265.1662650292&_gac=1.152436171.1694008758.Cj0KCQjwxuCnBhDLARIsAB-cq1qrnL244SZ9hRYSDTECPCq3oest-hy4Qs-AWuh-dz6GV2SJLkl8eoUaAki2EALw_wcB#unsafe-webhooks) because it selects namespaces like `kube-system`.

A traffic-manager that isn't namespaced must have a default namespace selector that looks like this:
```yaml
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - kube-node-lease
```
This default selector must be added under `agentInjector.webhook` in the `values.yaml` of the Helm chart so that a user can reconfigure it if needed.
