### ISSUE TITLE
Namespaced installation fails

### ISSUE THREAD

**Issue by cjreyn** [telepresenceio/telepresence#3404]
**Describe the bug**
We operate a multi-tenant cluster and wish to have users install their own instances in namespaces they control. The telepresence docs suggest this is possible. However a cluster scoped component `MutatingWebhookConfiguration`  prevents installation.

**To Reproduce**
Install via helm into a namespace named "xml46447" using the following values.yml

```
 managerRbac:
  create: true
  namespaced: true
  namespaces:
  -xml46447
clientRbac:
  create: true
  subjects:
    - kind: User
      name: xml46447
      apiGroup: rbac.authorization.k8s.io
  namespaced: true
  namespaces:
  - xml46447
client:
  dns:
    includeSuffixes:
    - .ac.uk
ambassador-agent:
  enabled: false
```

Produces:
```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource MutatingWebhookConfiguration "agent-injector-webhook-xml46447" in namespace "": mutatingwebhookconfigurations.admissionregistration.k8s.io "agent-injector-webhook-xml46447" is forbidden: User "xml46447" cannot get resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
```

**Expected behavior**
If a namespaced installation is supported, no cluster scoped components should be used. Ideally the helm chart should allow the `MutatingWebhookConfiguration` part of the template to not be installed. Then we can use manual injection as per:

https://www.getambassador.io/docs/telepresence-oss/latest/reference/intercepts/manual-agent

**Versions (please complete the following information):**
Client     : v2.16.1
RHEL8
Kubeadm 1.27
