### ISSUE TITLE
lists only deployments, not services

### ISSUE THREAD

**Issue by JCzz** [telepresenceio/telepresence#3407]
telepresence version
OSS Client         : v2.16.1
OSS Root Daemon    : v2.16.1
OSS User Daemon    : v2.16.1
OSS Traffic Manager: v2.16.1

telepresence list
echo-deployment: ready to intercept (traffic-agent already installed)

From this yaml, I would expect service to be interceptable
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - name: http
          containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: service-port
      port: 80
      protocol: TCP
      targetPort: http
```

But it is the deployment, which is fine, but I would expect the service... why is that?

Also that is what is in the getting started guide: https://www.getambassador.io/docs/telepresence-oss/latest/quick-start

Thanks in advance
