### ISSUE TITLE
Intercept multiple ports

### ISSUE THREAD

**Issue by alphashr** [telepresenceio/telepresence#3423]
Cannot intercept multiple ports. 

I saw this [ticket](https://github.com/telepresenceio/telepresence/issues/2570), but it's not 100% clear whether it's expected to work after the mentioned release or this is really a limitation of OSS version.

```bash
telepresence intercept foo-services --port 10082:10082
telepresence intercept foo-services-1 --workload foo-services --port 10052:10052 
```

**Error**
telepresence intercept: error: connector.CreateIntercept: Failed to establish intercept: intercept in error state AGENT_ERROR: **Conflicts** with the currently-served intercept "80ff9254-ddb8-4217-aabd-eec15487adf5:am│2023-11-09 10:32:07.3944 error   connector/server-grpc/conn=247 : sshfs not installed: exec: "sshfs": executable file not found in $PATH
p-services"

**Expected behavior**
Should be able to ports simultaneously. 

**Versions**
```
OSS Client         : v2.16.1
OSS Root Daemon    : v2.16.1
OSS User Daemon    : v2.16.1
OSS Traffic Manager: v2.16.1
```

**Comment by knlambert** [comment]
The OSS doesn't have such limitation.

Can you give us more informations on your service / deployments ?

**Comment by alphashr** [comment]
Sure. The deployment is istio with multiple ports:
```yaml
         ports:
         - containerPort: 10029
           name: http-test
           protocol: TCP
         - containerPort: 10030
           protocol: TCP
         - containerPort: 10031
           protocol: TCP
         - containerPort: 10084
           protocol: TCP
         - containerPort: 10067
```

With multiple services exposing them:
```
service-1             ClusterIP      10.12.22.17    <none>        10029/TCP        50d
service-2             ClusterIP      10.12.22.18    <none>       10030/TCP        50d
...
```

When I do the first intercept, everything looks good:

```
telepresence intercept service-1 --port 10029:10029
```

While the first intercept is in place, I try to add a new intercept:
```
telepresence intercept service-2 --workload foo-services --port 10030:10030
```
I get the above-mentioned error. 

Either i am using the cli in a wrong way, or there should be something wrong. Referring to this [post](https://github.com/telepresenceio/telepresence/issues/2570) the user had similar issue.

**Comment by knlambert** [comment]
When you say that the deployment is istio, do you mean it has an istio side car ? Or that you're intercepting istio itself ?

**Comment by cindymullins-dw** [comment]
Just to add to this, you wouldn’t be intercepting Istio, nor an Istio sidecar.  Instead you would intercept whatever app container you’re trying to debug.  What does your entire deployment look like - if you can share that we can tell you what Telepresence can and can’t intercept.

**Comment by alphashr** [comment]
@knlambert yes, the app has Istio side car.

**Comment by lkoniecz** [comment]
same here

```
telepresence intercept java-server-mobile --workload java-server --service=java-server-external --port 1035:1035 --mechanism=tcp --mount=false
Using StatefulSet java-server
   Intercept name         : java-server-mobile
   State                  : ACTIVE
   Workload kind          : StatefulSet
   Destination            : 127.0.0.1:1035
   Service Port Identifier: tcp-1035
   Intercepting           : all TCP connections
   ```

so far, so good

```
telepresence intercept java-server-native --workload java-server --service=java-server-internal --port 1036:1036 --mechanism=tcp --mount=false
telepresence intercept: error: connector.CreateIntercept: Failed to establish intercept: intercept in error state AGENT_ERROR: Conflicts with the currently-served intercept "995b76f2-74c9-4cd7-8748-e716449d32d3:java-server-mobile"

See logs for details (1 error found): "/Users/lky/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

backend and client on `v2.16.1`

java-server-internal
```
  ports:
  - name: tcp-1034
    nodePort: 31570
    port: 1034
    protocol: TCP
    targetPort: web
  - name: tcp-1035
    nodePort: 30240
    port: 1035
    protocol: TCP
    targetPort: mobile
```


java-server-internal
```
  ports:
  - name: tcp-1036
    port: 1036
    protocol: TCP
    targetPort: native
  - name: tcp-1037
    port: 1037
    protocol: TCP
    targetPort: remote
```    

it used to work on previous versions
