### ISSUE TITLE
Traffic agent fails to start up due to security context

### ISSUE THREAD

**Issue by bpfoster** [telepresenceio/telepresence#3515]
**Describe the bug**
Beginning in telepresence v2.15.1, trying to intercept a service whose container defines a restrictive `securityContext` leads to the traffic agent failing to start.  This looks to be caused by the changes in that version to `agentconfig.container`, where the security context of the first container is now copied to the traffic agent.

**To Reproduce**
1. When I run `telepresence intercept "${SERVICE_NAME}"`
2. I see 
```
telepresence intercept: error: connector.CreateIntercept: Back-off restarting failed container traffic-agent in pod SERVICE_NAME-cd6f7df8d-mzwsm_default(ca141105-a99b-4f59-aaea-8e0ff9159427)
The logs of Pod SERVICE_NAME-cd6f7df8d-mzwsm might provide more detai
```
4. So I look at the logs for the traffic-agent container in that pod and see
```
exec /usr/local/bin/traffic: operation not permitted
```

**Expected behavior**
A successful intercept.

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
OSS Client         : v2.18.0
OSS Root Daemon    : v2.18.0
OSS User Daemon    : v2.18.0
OSS Traffic Manager: v2.18.0
Traffic Agent      : docker.io/datawire/tel2:2.18.0
```
 - Operating system of workstation running `telepresence` commands
```
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
```
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
```
kind v0.21.0 go1.20.13 linux/amd64
```

**Additional context**
The security context of the main container, that I can see is copied to the traffic-agent container, is:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001
  seccompProfile:
    type: RuntimeDefault
```
