### ISSUE TITLE
allowConflictingSubnets not recognised in laptop config.yml

### ISSUE THREAD

**Issue by craftey** [telepresenceio/telepresence#3613]
I have a subnet issue with my cluster:
```
$ telepresence connect --namespace dev
telepresence connect: error: connector.Connect: subnet 169.254.169.252/30 overlaps with existing route "169.254.0.0/16 via 10.5.56.32 dev en0, gw <nil>". Please see https://www.getambassador.io/docs/telepresence/latest/reference/vpn for more information

```
I can fix this by:
```
$ telepresence connect --namespace dev --allow-conflicting-subnets 169.254.169.254/30
Connected to context gke_..., namespace dev (https://x.x.x.x/)

```
I can also fix this by adding
```
client:
  routing:
    allowConflictingSubnets:
    - 169.254.169.254/30
```
to the helm chart values.

What NOT seems to work is putting the same into `~/Library/Application\ Support/telepresence/config.yml` .
I tried:
```
client:
  routing:
    allowConflictingSubnets:
    - 169.254.169.254/30
```
and
```
routing:
  allowConflictingSubnets:
  - 169.254.169.254/30
```

I can work with putting it into the helm values or as cli option.

But I think that it is not working with local laptop-side config is a bug.

Tested with telepresence v2.19.5 on macOS.
