### ISSUE TITLE
intercept: Dependent environment variable not being expanded

### ISSUE THREAD

**Issue by akojo** [telepresenceio/telepresence#3680]
**Describe the bug**

I'm passing k8s node's host IP to an application via an environment variable and during intercept the variable's value doesn't get expanded. This happens consistently (which means the root cause is probably different than in #2853)

**To Reproduce**

1. I have a service with environment variable definitions:

    ```yaml
    spec:                                                                                                                                                                           
      containers:                                                                                                                                                                   
      - env:                                                                                                                                                                        
        - name: HOST_IP                                                                                                                                                             
          valueFrom:                                                                                                                                                                
            fieldRef:                                                                                                                                                               
              apiVersion: v1                                                                                                                                                        
              fieldPath: status.hostIP                                                                                                                                              
        - name: OTEL_EXPORTER_OTLP_ENDPOINT                                                                                                                                         
          value: http://$(HOST_IP):4317
    ```

2. When I run `telepresence intercept` for the service `$(HOST_IP)` in `OTEL_EXPORTER_OTLP_ENDPOINT` doesn't get expanded, e.g.

    ```sh
    $ telepresence intercept ui-421a635a -- env | grep OTEL
    OTEL_EXPORTER_OTLP_ENDPOINT=http://$(HOST_IP):4317
    ```

**Expected behavior**

Environment variable gets expanded into remote environment.

**Versions (please complete the following information):**

 - Output of `telepresence version`

    ```
    OSS Client         : v2.19.1
    OSS Root Daemon    : v2.19.1
    OSS User Daemon    : v2.19.1
    OSS Traffic Manager: v2.19.1
    Traffic Agent      : docker.io/datawire/tel2:2.19.1
    ````

 - Operating system of workstation running `telepresence` commands

    Ubuntu 22.04

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]

    Minikube v1.33.1

**Additional information**

Running a shell inside the same container I get:

```sh
app@ui-421a635a-7774989488-fb2gk:/app$ env | grep OTEL
OTEL_EXPORTER_OTLP_ENDPOINT=http://192.168.49.2:4317
```

as expected
