### ISSUE TITLE
Init container is getting injected when there is a numeric port despite it not being intercepted

### ISSUE THREAD

**Issue by Mapmo** [telepresenceio/telepresence#3730]
**Describe the bug**
When doing  telepresence intercept on my cluster, it fails for deployments that have more than one containerPort and the targetPorts for that conatainerPort is numeric. The reason for the failure is is that the init container tel-agent-init is being injected and throws the error:
```
tel-agent-init 2024-11-21 11:31:51.9193 info    Traffic Agent Init v2.20.0
tel-agent-init 2024-11-21 11:31:51.9271 error   failed to clear chain TEL_PREROUTING_TCP: running [/sbin/iptables -t nat -N TEL_PREROUTING_TCP --wait]: exit status 4: iptables v1.8.10 (nf_tables): Could not fetch rule set generation  ││ id: Permission denied (you must be root)
tel-agent-init
tel-agent-init 2024-11-21 11:31:51.9272 error   quit: failed to clear chain TEL_PREROUTING_TCP: running [/sbin/iptables -t nat -N TEL_PREROUTING_TCP --wait]: exit status 4: iptables v1.8.10 (nf_tables): Could not fetch rule set gener ││ ation id: Permission denied (you must be root)
tel-agent-init  
```
Note 1: https://www.getambassador.io/docs/telepresence/latest/troubleshooting#injected-init-container-doesnt-function-properly does mentions this issue, but doesn't specify that all ports for the deployment need to be named in their respective services. The steps to reproduce that I will give are for a simplified example that also reproduces the issue, but in my original case, the numeric targetPort was in a separate service which made debugging the issue harder.
Note 2: While the example I am giving is not throwing an error, the issue with the init container getting created can be seen there.

**Workaround**
 By naming the numeric targetPort the issue is solved.

**To Reproduce**
1.Create a deployment with the following container ports
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9091
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
```
2. Create a service with the following ports
```
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
  labels:
    app: busybox
spec:
  selector:
    app: busybox
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: 9091
```
3. Intercept the deployment
```
telepresence intercept busybox-deployment --port 8081:8081
```
4. Check if the pod has an init container
```
kubectl get pods -l app=busybox  -o yaml | grep init
```
- Expected: there is not
- Actual: there is
5. Change the services so that port metrics has a named targetPort  called metrics the problem is solved
```
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
  labels:
    app: busybox
spec:
  selector:
    app: busybox
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  - name: metrics
    port: 9091
    protocol: TCP
    targetPort: metrics
```
6. Leave the previous intercept and intercept again
```
telepresence leave busybox-deployment
telepresence intercept busybox-deployment --port 8081:8081
```
7. Check if the pod has an init container again
```
kubectl get pods -l app=busybox  -o yaml | grep init
```
- Expected: there is not
- Actual: there is

**Expected behavior**
In both situations there should not have been an init container, because the intercepted port is named.

**Versions (please complete the following information):**
 - Output of `telepresence version`
$ telepresence version
OSS Client         : v2.20.0
OSS Root Daemon    : v2.20.0
OSS User Daemon    : v2.20.0
OSS Traffic Manager: v2.20.0
 - Operating system of workstation running `telepresence` commands
WSL on windows running ubuntu 22.04
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
rancher v1.29.0+rke2r1
