### ISSUE TITLE
Intercept 8080:http not working, service still not accessible via ingress without telepresence

### ISSUE THREAD

**Issue by assayire** [telepresenceio/telepresence#3780]
I have configured my service manifest as instructed in [**this**](https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports) documentation. It was earlier suggested in one of the issue that I had raised.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: ...
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector: ...
...

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  labels: ...
  annotations: ...
spec:
  replicas: 1
  selector: ...
  template:
    metadata: ...
    spec:
      imagePullSecrets:
        - name: artifactory

      serviceAccountName: my-service-job-sa

      securityContext:
        runAsGroup: 9999
        runAsUser: 9999

      terminationGracePeriodSeconds: 45

      containers:
        - name: my-service
          image: ...
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: my-service-sm-secret-kv
          env: ...
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          ...

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-my-service-ingress
  labels: ...
  annotations: ...
spec:
  tls:
    - hosts:
      - "my-service-default.public.dev.mydomain.com"
      secretName: 
  rules:
    - host: "my-service-default.public.dev.mydomain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 8080
```

But i am not able to intercept using the following command:

```bash
telepresence intercept my-service
```

... gives the following error:

```
telepresence intercept: error: connector.CreateIntercept: Deployment my-service.my-namespace has no interceptable port matching port http
```

Also ... without any of telepresence, deploying my service to the cluster, i am not able to access the service using the ingress. Gives 503 error.
