### ISSUE TITLE
Helm chart path "fix"

### ISSUE THREAD

**Issue by mike-sirs** [telepresenceio/telepresence#3801]
This is rather an improvements than a bug fix. 
To allow telepresence-oss to be installed  using argocd will require dir name change.

currently if you pull `helm pull oci://ghcr.io/telepresenceio/telepresence-oss` oci chart and untar it
you'll find `telepresence` dir and not `telepresence-oss`. While it isn't RFC that small change will allow to use gitops to install  telepresence-oss.

**To Reproduce**
add argocd application
```
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: telepresence
spec:
  generators:
    - list:
        elements:
          - env: dev
            cluster-name: cluster
  template:
    metadata:
      name: "telepresence-{{env}}"
    spec:
      project: telepresence
      sources:
        # Chart with updated dir/path  >> `ghcr.io/mike-sirs/helm-oci`
        - repoURL: elepresence-oss:2.21.3/telepresence
          chart: telepresence-oss
          targetRevision: 2.21.3
          helm:
            releaseName: telepresence
            values: |
              agentInjector:
                enabled: false
```
argo wont be able to find Chart.yaml since it expects `telepresence-oss/Chart.yaml instead of telepresence/Chart.yaml`
