### ISSUE TITLE
Can not use Telepresence as Helm chart dependency

### ISSUE THREAD

**Issue by Blarc** [telepresenceio/telepresence#3833]
I have the following `Chart.yaml`:
```yaml
apiVersion: v2
dependencies:
  - name: telepresence-oss
    repository: oci://ghcr.io/telepresenceio/telepresence-oss
    version: 2.22.2
    condition: enabled
description: Helm chart to deploy telepresence
name: telepresence-oss
version: 1.0.0
```

When I run command `helm dependencies update` or  `helm dependencies build`, I get the following response:
```
Downloading telepresence-oss from repo oci://ghcr.io/telepresenceio/telepresence-oss
Save error occurred:  could not download oci://ghcr.io/telepresenceio/telepresence-oss/telepresence-oss: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Atelepresenceio%2Ftelepresence-oss%2Ftelepresence-oss%3Apull&service=ghcr.io: 403 Forbidden
Error: could not download oci://ghcr.io/telepresenceio/telepresence-oss/telepresence-oss: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Atelepresenceio%2Ftelepresence-oss%2Ftelepresence-oss%3Apull&service=ghcr.io: 403 Forbidden
```

I want to have telepresence as Helm chart dependency so I can deploy it with GitOps and have Renovate watch it for automatic updates.

**Comment by thallgren** [comment]
OCI support was experimental in Helm versions prior to 3.8. What version are you using? This [Helm documentation](https://helm.sh/docs/topics/registries/) might be helpful.

**Comment by Blarc** [comment]
> OCI support was experimental in Helm versions prior to 3.8. What version are you using? This [Helm documentation](https://helm.sh/docs/topics/registries/) might be helpful.

```
> helm version
version.BuildInfo{Version:"3.16.4", GitCommit:"7877b45b63f95635153b29a42c0c2f4273ec45ca", GitTreeState:"clean", GoVersion:"go1.22.9"}
```

**Comment by thallgren** [comment]
This [documentation](https://helm.sh/docs/topics/registries/#specifying-dependencies) states:

> The repository for a given entry in Chart.yaml is specified as the registry reference without the basename

So your dependencies should probably look like this:
```yaml
dependencies:
  - name: telepresence-oss
    repository: oci://ghcr.io/telepresenceio
    version: 2.22.2
    condition: enabled
```

**Comment by Blarc** [comment]
:facepalm: Thanks a lot.

**Comment by Blarc** [comment]
I've run the `helm dependencies build` command which now passes and charts folder is created. I've now tried running
`helm install telepresence-oss . --dry-run` which fails:
```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
telepresence-oss:
- (root): Additional property global is not allowed
```

**Comment by thallgren** [comment]
So where does this additional "global" property come from? Telepresence has no such property.

**Comment by Blarc** [comment]
> So where does this additional "global" property come from? Telepresence have no such property.

I have no idea. I tried doing this from scratch and I get the same error. Here are the steps:
```
cd /tmp && mkdir telepresence && cd telepresence
```
```
cat > Chart.yaml <<EOF                                                                                                                                                                                                                                                                              
apiVersion: v2
dependencies:
  - name: telepresence-oss
    repository: oci://ghcr.io/telepresenceio
    version: 2.22.2
    condition: enabled
description: Helm chart to deploy telepresence
name: telepresence-oss
version: 1.0.0
EOF
```
```
helm dependency build . && helm install telepresence-oss . --dry-run
```

Result:
```
...
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading telepresence-oss from repo oci://ghcr.io/telepresenceio
Pulled: ghcr.io/telepresenceio/telepresence-oss:2.22.2
Digest: sha256:d6ce398ec1c67542b969490d2b5949c575ea14c11d7b9109b250301e1944b856
Deleting outdated charts
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
telepresence-oss:
- (root): Additional property global is not allowed
```
