### ISSUE TITLE
VPN Disconnection Quits Telepresence User Docker Daemon

### ISSUE THREAD

**Issue by natejohnsimonsen** [telepresenceio/telepresence#3855]
**Describe the bug**
When I disconnect from my VPN, after about 10~30 seconds my Docker User Daemon quits and leaves my intercept in my cluster.

Context:
VPN: AWS VPN 3.6
OS: MacOS
Docker: Yes
K8S Provider: EKS 1.31
TP Versions:
OSS Client             : v2.22.4
OSS Daemon in container: v2.22.4
OSS Traffic Manager    : v2.22.4
Traffic Agent          : ghcr.io/telepresenceio/tel2:2.22.4

TP config used (verified it was in the docker path `/root/.config/telepresence/config.yml` (happened with / without these set):

```
timeouts:
  trafficManagerAPI: 10m
  helm: 90s
  clusterConnect: 10m
  connectivityCheck: 5s
  endpointDial: 10m
  roundtripLatency: 10m
  intercept: 10m
  proxyDial: 10m
  trafficManagerConnect: 10m
```

**Logs**:
https://github.com/natejohnsimonsen/tmp-tp-logs
I had a problem uploading to GH so I created a repo with the zip file here.

Error seen in connecter.log
```
2025-05-01 22:10:04.5639 error   docker/api-orders/dns/Server : Lookup AAAA "redis-master.": rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**To Reproduce**
1. Connect to VPN
2. run `tp connect --namespace ns-name --manager-namespace ns-name --mapped-namespaces ns-name,other-ns-name --docker --name svc-name ; tp replace svc-name --env-file=./env-file`
3. Disconnect from VPN
4. Wait for 10~30 seconds
5. The User Daemon quits itself and the intercept still exists in the cluster. 

**Expected behavior**
I expect there is a timeout that can be set (either locally or preferably in the helm chart) to specify a timeout so that telepresence won't quit if the VPN connection is dropped.

**Additional Notes**
We are running our control plane and all resources in private subnets that can only be reached when connected to the VPN.
