### ISSUE TITLE
Telepresence intercept fails in conjunction with knative-eventing's queue-proxy

### ISSUE THREAD

**Issue by sbaier1** [telepresenceio/telepresence#3871]
**Describe the bug**
I'm trying to use telepresence with containers that run a queue-proxy sidecar from knative-eventing.

Might also be related to https://github.com/telepresenceio/telepresence/issues/1029

This fails hard, as telepresence agent tries to intercept all ports in the pod, even though it doesn't make much sense in this case, and in the process it seems to spawn thousands of unnecessary goroutines (for a reason i don't fully comprehend) and causes issues such as high cpu load on affected pods.

**To Reproduce**
1. Run a knative-eventing workload with queue-proxy sidecar (in my case, the root workload is a knative Service CR, combined with a Trigger CR from eventing)
2. Set telepresence log level to debug
3. Use pod mutation hook annotations:

```yaml
annotations:
  telepresence.io/inject-container-ports: "8080"
  telepresence.io/inject-traffic-agent: enabled
```

4. Observe telepresence agent logs trying to forward to queue-proxy

**Expected behavior**

Telepresence should either:
- only connect forward to ports specified in inject-container-ports, as i expect them to be an explicit configuration rather than a suggestion
- or: allow excluding containers from agent's forwarding logic, [which is currently not possible as i understand the code here](https://github.com/telepresenceio/telepresence/blob/945b5595f7f8f637197190a541f3876182c30a7e/pkg/agentmap/generator.go#L162-L171)

(i guess manual injection could also be a workaround(?) but is also pretty high-effort to workaround a pretty minor issue)

**Versions (please complete the following information):**
 - Version: 2.22.6
 - Operating system of workstation running `telepresence` commands: macOS
 - Kubernetes environment and Version K3s on bare metal, version v1.30.11+k3s1

**Additional context**

[telepresence-agent-fail.log](https://github.com/user-attachments/files/20595147/telepresence-agent-fail.log)

Here's an excerpt of the container spec of the queue-proxy container: it seems that telepresence is trying to forward to a metric port. I am still not sure why it's failing in this exact way at this point, maybe queue-proxy isn't listening on the specified port, but in that case, telepresence agent should fail gracefully IMO.

```yaml
      name: queue-proxy
      ports:
      - containerPort: 8022
        name: http-queueadm
        protocol: TCP
      - containerPort: 9090
        name: http-autometric
        protocol: TCP
      - containerPort: 9091
        name: http-usermetric
        protocol: TCP
      - containerPort: 8012
        name: queue-port
        protocol: TCP
      - containerPort: 8112
        name: https-port
        protocol: TCP

```
