### ISSUE TITLE
Ambassador routing cannot connect to replaced pod

### ISSUE THREAD

**Issue by erik-sn** [telepresenceio/telepresence#790]
I am running a fairly standard web application stack in a minikube cluster locally. The two services of concern are the API gateway (running Ambassador) and the API application (running Python/Django if it matters).

I have an Ambassador route directing all traffic with the API prefix to the api service on port 8000:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  httpbin_mapping
      prefix: /httpbin/
      service: httpbin.org:80
      host_rewrite: httpbin.org
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  api_service
      prefix: /
      rewrite: /
      service: mako-api:8000
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
    service: ambassador
```

This is working as expected, visiting `{minikube url}/httpbin/ip` returns the response from httbin.org, and all other requests are successfully routed to Django which is internally running on port 8000. The problem occurs when I telepresence the api container with my local container:

`telepresence --swap-deployment mako-api --docker-run -p 8000:8000  -it -v $(pwd)/api:/code --entrypoint "/bin/bash" mako_api:latest`

After this succeeds I can successfully start the Django server `python manage.py runserver 0.0.0.0:8000`.

The pod is successfully replaced and the service is running the correct pod according to the minikube dashboard. Due to the `-p 8000:8000` I can access the application successfully on `localhost:8000` (so far so good).  Visiting `{minikube url}/httpbin/ip` still works, but now all other endpoints instead of being routed to Django return a 503 status code and the ambassador/envoy message:

```
upstream connect error or disconnect/reset before headers
```

Here is a log entry from ambassador that basically says the same thing, but I did confirm the target IP address is correct:

```
ACCESS [2018-09-27T21:24:42.043Z] "GET /api/admin HTTP/1.1" 503 UF 0 57 0 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36" "17079714-575d-4696-97c4-bb739b0a1414" "192.168.99.100:30220" "10.108.123.42:8000"
```

If I stop the telepresence connection, the expected behavior returns. I am wondering if anyone can point me in a direction to continue troubleshooting.

Update: Found the issue. I just had to add `--expose 8000` to my telepresence command and all is well.
